src/p2p/net_node.inl

- Add more seednodes
- Correct testnet seednodes port

Update testnet/main default seednodes

---

src/cryptonote_core/cryptonote_core.cpp
src/cryptonote_core/cryptonote_core.h

Read more https://getmonero.org/2017/05/17/disclosure-of-a-major-bug-in-cryptonote-based-currencies.html
From Monero patch #1744. Credit @fluffypony

Urgent fix for security bug

---

src/cryptonote_core/cryptonote_core.cpp
src/daemon/command_parser_executor.cpp
src/daemon/command_server.cpp
src/daemon/rpc_command_executor.cpp

Cause: Fee accumulated from previous txes due to a bug
- Improve print_coinbase_tx_sum command help/error texts

Fix misleading total fee from get_coinbase_tx_sum function

---

src/cryptonote_config.h
src/cryptonote_core/blockchain.cpp
src/cryptonote_core/difficulty.cpp
src/cryptonote_core/difficulty.h

Reverts sumoprojects/sumokoin#10

Revert "Adjust difficulty calculation algorithm"

---

src/cryptonote_config.h
src/cryptonote_core/difficulty.cpp

Adjust difficulty calculation algorithm (ver 5.3)

---

src/wallet/wallet_rpc_server.cpp
src/wallet/wallet_rpc_server_commands_defs.h

Patch from: https://github.com/monero-project/monero/pull/2121
Credit @binaryFate

Return per-tx amount in transfer_split RPC call

---

src/cryptonote_core/cryptonote_format_utils.cpp
src/cryptonote_core/cryptonote_format_utils.h
src/cryptonote_core/tx_extra.h
src/simplewallet/simplewallet.cpp
src/wallet/api/wallet.cpp
src/wallet/wallet2.cpp
src/wallet/wallet2.h
src/wallet/wallet_errors.h
src/wallet/wallet_rpc_server.cpp
src/wallet/wallet_rpc_server.h

This is the next and final part of "Subaddresses" feature for Sumokoin (continued from Part 1 #28)
- Support transfer to multiple subaddresses or mix of standard + subaddresses
- Clean up code for better performance

Subaddresses (Part 2)

---

contrib/epee/include/net/http_client.h
contrib/epee/include/net/net_helper.h

This is needed for allowing the mobile wallet to use SSL connections with the node.

Add SSL support to the http client / net helper.

---

Dockerfile
src/daemon/executor.cpp
src/daemon/executor.h
src/daemonizer/posix_daemonizer.inl

Dockerfile for Sumokoin

---

src/cryptonote_core/cryptonote_core.cpp

As Sumokoin doesn't fork periodically like Monero

Remove scheduled hardfork warnings

---

contrib/epee/include/net/net_helper.h
src/cryptonote_config.h
src/simplewallet/simplewallet.cpp
src/simplewallet/simplewallet.h
src/wallet/wallet2.h

Due to bugs in net socket code
- Some other wallet potential bugs

Fix slow wallet scan

---

src/crypto/cn_slow_hash.hpp
src/crypto/cn_slow_hash_hard_intel.cpp
src/crypto/cn_slow_hash_soft.cpp
src/cryptonote_config.h
src/cryptonote_core/blockchain.cpp
src/cryptonote_core/blockchain.h
src/cryptonote_core/cryptonote_format_utils.cpp
src/cryptonote_core/cryptonote_format_utils.h
src/cryptonote_core/miner.cpp

As usual, please ignore whitespace on diffs

Intergrate cn_heavy

---

src/crypto/cn_slow_hash.hpp

Use boost for aligned alloc

---

CMakeLists.txt
src/crypto/CMakeLists.txt
src/crypto/cn_slow_hash.hpp
src/crypto/cn_slow_hash_hard_arm.cpp
src/crypto/cn_slow_hash_soft.cpp

This PR adds support for NEON and hardware AES on armv8 as well as working around what appears to be a CPU bug on armv7.
Ready for review and merge

Hardware arm support

---

src/simplewallet/simplewallet.cpp
src/wallet/wallet2.cpp

Often happened when creating wallet at disconnected mode

 Fix wallet infinite scanning due to wrong timestamp

---

src/simplewallet/simplewallet.cpp
src/wallet/api/wallet_manager.cpp
src/wallet/wallet2.cpp

- Made the scanning code ignore OptimiseCoinbase mode, pending total removal
- Fixed amount = 0 on coinbase outputs, affected wallets need a re-scan.

Fix coinbase output amounts

---

contrib/epee/include/storages/portable_storage_from_bin.h
src/wallet/wallet2.cpp

Merge from https://github.com/monero-project/monero/pull/4438
More info: https://getmonero.org/2018/09/25/a-post-mortum-of-the-burning-bug.html
Note: file "contrib/epee/include/storages/portable_storage_from_json.h" was already patched from code base v0.12.3.0

Fix critical Monero burning bug

---

external/unbound/libunbound/python/examples/dnssec_test.py
src/common/dns_utils.cpp

This PR updates the KSK trust anchor used in sumokoin. See icann.org/resources/pages/ksk-rollover for more info

Update root trust anchor key 

---

src/simplewallet/simplewallet.cpp
src/simplewallet/simplewallet.h
src/wallet/wallet2.cpp
src/wallet/wallet2.h
src/wallet/wallet_rpc_server.cpp
src/wallet/wallet_rpc_server_commands_defs.h

Add **non** destructive blockchain rescan to wallet

Non destructive blockchain rescan

---

src/daemon/rpc_command_executor.cpp

Reverts sumoprojects/sumokoin#160

Revert "Print a human friendly timestamp"

---

src/wallet/wallet_rpc_server.cpp
src/wallet/wallet_rpc_server.h
src/wallet/wallet_rpc_server_commands_defs.h

- COMMAND_RPC_GENERATE_FROM_KEYS
- COMMAND_RPC_RESTORE_DETERMINISTIC_WALLET

Add new RPC commands for GUI wallet

---

src/cryptonote_core/blockchain.cpp

Update blockdata checksum

---

src/device/device_ledger.cpp

Unimportant for the time being cause we are not supported by ledger but correction is needed for web wallet (open monero) compiling

change Monero Version to Sumokoin

---

contrib/epee/include/serialization/keyvalue_serialization.h
contrib/epee/include/serialization/keyvalue_serialization_overloads.h
contrib/epee/src/mlog.cpp

from commit https://github.com/monero-project/monero/commit/7a9316ebef2336caad9d2ea0babd10abc9a93925

[Serialization] set default log category

---

contrib/epee/src/net_ssl.cpp

From PR https://github.com/monero-project/monero/pull/5509

[EPEE] net_ssl: SSL config tweaks for compatibility and security

---

contrib/epee/include/net/net_ssl.h
contrib/epee/src/net_ssl.cpp
src/device_trezor/device_trezor_base.cpp
src/device_trezor/trezor/transport.cpp
src/device_trezor/trezor/transport.hpp
src/rpc/core_rpc_server.cpp
src/wallet/wallet2.cpp
src/wallet/wallet_rpc_server.cpp
tests/functional_tests/functional_tests_rpc.py
tests/unit_tests/output_distribution.cpp

- net_ssl: allow sha256 fingerprints only
- wallet_rpc_server: fix crash in validate_address if no wallet is loaded,
fix return value on error
Up to: https://github.com/monero-project/monero/commit/2bf855e3cdfe2726e07cf5f4f4e6f69219e498a6

[ALL] Update code

---

cmake/FindBacktrace.cmake
contrib/depends/Makefile
contrib/depends/packages/gtest.mk
contrib/depends/packages/native_cctools.mk
contrib/depends/packages/native_cmake-unused.mk
contrib/depends/packages/packages.mk
contrib/depends/toolchain.cmake.in
contrib/epee/include/net/net_ssl.h
contrib/epee/include/rolling_median.h
contrib/epee/src/net_ssl.cpp
src/cryptonote_core/blockchain.cpp
src/cryptonote_core/blockchain.h
src/daemon/rpc_command_executor.cpp
src/p2p/net_node.inl
src/p2p/net_peerlist.h
src/p2p/p2p_protocol_defs.h
src/rpc/core_rpc_server.cpp
src/rpc/daemon_handler.cpp
src/rpc/rpc_handler.cpp
src/rpc/rpc_handler.h
src/wallet/wallet2.cpp
src/wallet/wallet_rpc_server.cpp
tests/CMakeLists.txt
tests/functional_tests/functional_tests_rpc.py
tests/functional_tests/get_output_distribution.py
tests/hash-target.cpp
tests/unit_tests/CMakeLists.txt
tests/unit_tests/output_distribution.cpp
tests/unit_tests/rolling_median.cpp
tests/unit_tests/uri.cpp

- net_ssl: SSL config tweaks for compatibility and security
- cmake: fix some case of "backtrace lib not found" breaking
- wallet2: reject standalone short payment IDs in monero: URI API
- wallet_rpc_server: reject standalone short payment id in address book
- wallet2: fix infinite loop picking outputs in corner case
- blockchain: keep a rolling long term block weight median
- rpc: improve get_output_distribution
- p2p: do not send last_seen timestamp to peers
Up to upstream commit https://github.com/monero-project/monero/commit/c0bc6d96cd67071e433b473bfb76a113529b1deb

[ALL] Update dev code

---

README.i18n.md
README.md
contrib/depends/README.md
contrib/depends/packages.md
contrib/gitian/README.md
src/common/password.cpp
src/simplewallet/simplewallet.cpp
src/simplewallet/simplewallet.h
src/wallet/api/wallet.cpp
src/wallet/wallet2.cpp
src/wallet/wallet2.h
tests/README.md
tests/gtest/README.md

- Update README
- password: do not use line input on windows
Up to upstream https://github.com/monero-project/monero/commit/5fbfa8a65663e807c6500ae9485e898df9b7c470

[WALLET] Add unlock_time details to show_transfers

---

cmake/GenVersion.cmake
contrib/depends/packages/packages.mk
contrib/depends/toolchain.cmake.in
contrib/gitian/gitian-linux.yml
contrib/gitian/gitian-osx.yml
contrib/gitian/gitian-win.yml
src/blockchain_utilities/README.md
translations/monero.ts
translations/monero_fr.ts
translations/monero_it.ts
translations/monero_ja.ts
translations/monero_sv.ts

- Don't use -march=native
- Allow parallel make
- Delete redundant cppzmq dependency
- Use 9 digit build IDs
- Update translations
Up to upstream/master https://github.com/monero-project/monero/commit/7b3df89bd4b7049ecb19171a271aa46d286c3bb5

[MISC] Build fine-tuning, update translations

---

src/daemon/rpc_command_executor.cpp

Ref: https://github.com/monero-project/monero/pull/5659/commits/31212e225dc4629853bb49167018708d93f83e93

[Daemon] Print 128bit diff properly

---

src/cryptonote_core/cryptonote_core.cpp

Ref: https://github.com/monero-project/monero/pull/5664/commits/c1eba2b5872cb4ac49ed0adaffc878d688701b32

[Core] Fix --prune-blockchain not pruning if no blockchain exists

---

src/rpc/CMakeLists.txt

Ref: https://github.com/monero-project/monero/pull/5689/commits/1db5357c7b0ee6a0beffe993eb618b4881c871b9

[RPC] Fix RPC header included at CMakeLists.txt

---

contrib/depends/packages/hidapi.mk

Ref: https://github.com/monero-project/monero/pull/5704/commits/8f2227940de8c270d2e4636bc91d0a4f6af36f65

[Depends] Update to HIDAPI v0.9.0 from master branch

---

src/crypto/cn_heavy_hash.hpp

[CRYPTO] Make heavy hash work at cross-compiling for MINGW

---

src/cryptonote_core/blockchain.cpp
src/wallet/wallet2.cpp

to get rid of compiler warnings

[MISC] Init and remove unused variables

---

src/cryptonote_protocol/cryptonote_protocol_handler.inl
src/p2p/net_node.inl

- [cryptonote_protocol] Drop peers we can't download from when syncing
Ref: https://github.com/monero-project/monero/pull/5732/commits

[P2P] Add missing connection close calls

---

CMakeLists.txt
src/CMakeLists.txt
src/debug_utilities/CMakeLists.txt
src/debug_utilities/dns_checks.cpp

Ref: https://github.com/monero-project/monero/pull/5451/commits

[DNS] New helper program to check on DNSSEC lookups

---

src/simplewallet/simplewallet.cpp
src/simplewallet/simplewallet.h

Ref: https://github.com/monero-project/monero/pull/5460/commits/a23dbe69f66aa592b5e30a125e9d16bd27ef57d9

[Wallet] Prompt when spending more than one old out in one tx

---

tests/functional_tests/blockchain.py
utils/python-rpc/framework/daemon.py

Ref: https://github.com/monero-project/monero/commit/ddf789073046ca7a396c159550d5896aa7de709b

[python-rpc] Add missing getblock RPC parameters

---

src/blockchain_db/lmdb/db_lmdb.cpp
src/blockchain_utilities/blockchain_blackball.cpp
src/cryptonote_core/blockchain.cpp
src/cryptonote_core/cryptonote_core.cpp
src/ringct/multiexp.cc
src/ringct/rctTypes.cpp
src/rpc/core_rpc_server.cpp
src/wallet/wallet2.cpp
tests/core_tests/chaingen.cpp
tests/core_tests/wallet_tools.cpp
tests/unit_tests/test_protocol_pack.cpp
tests/unit_tests/varint.cpp

Ref: https://github.com/monero-project/monero/pull/5502/commits

[MISC] Remove unused code and add some checks

---

src/blockchain_db/blockchain_db.h
src/blockchain_db/lmdb/db_lmdb.cpp
src/blockchain_db/lmdb/db_lmdb.h
src/blockchain_db/testdb.h
src/cryptonote_core/blockchain.cpp
src/cryptonote_core/blockchain.h
src/cryptonote_core/cryptonote_core.cpp

Alternative blocks are cleared on startup unless --keep-alt-blocks
is passed on the command line
Ref: https://github.com/monero-project/monero/pull/5524/commits

[BLOCKCHAIN] Keep alternative blocks in LMDB

---

contrib/epee/include/net/connection_basic.hpp
contrib/epee/src/connection_basic.cpp
contrib/rlwrap/monerocommands_bitmonerod.txt
src/daemon/command_parser_executor.cpp
src/daemon/command_parser_executor.h
src/daemon/command_server.cpp
src/daemon/rpc_command_executor.cpp
src/daemon/rpc_command_executor.h
src/p2p/net_node.cpp
src/p2p/net_node.h
src/p2p/net_node.inl
src/rpc/core_rpc_server.cpp
src/rpc/core_rpc_server.h
src/rpc/core_rpc_server_commands_defs.h

Ref: https://github.com/monero-project/monero/commit/6abaaaa994c79cbeea37f6b0079ca6b24ecef3a5

[DAEMON RPC] Remove obsolete save_graph skeleton code

---

src/wallet/api/wallet.cpp
src/wallet/api/wallet.h
src/wallet/api/wallet2_api.h

Ref: https://github.com/monero-project/monero/commit/4c666141e3ee68868ccea7dd34d5c1875378cf5a

[Wallet API] Expose get/set walletcache attribute in wallet api

---

src/daemon/command_parser_executor.cpp
src/daemon/rpc_command_executor.cpp
src/daemon/rpc_command_executor.h
src/p2p/net_node.h
src/p2p/net_node.inl
src/rpc/core_rpc_server.cpp
src/rpc/core_rpc_server_commands_defs.h

Ref: https://github.com/monero-project/monero/pull/5582

[CORE RPC] In/out peers can now return the setting's value

---

src/cryptonote_core/blockchain.cpp
src/cryptonote_protocol/cryptonote_protocol_defs.h
src/cryptonote_protocol/cryptonote_protocol_handler.inl

in NOTIFY_RESPONSE_GET_OBJECT
Ref: https://github.com/monero-project/monero/pull/5591/commits/f17dcde4513b7eb0603b46c1e76d8c01f1f1e5a0

[CORE] Remove unused txs member

---

src/cryptonote_protocol/cryptonote_protocol_defs.h
src/cryptonote_protocol/cryptonote_protocol_handler.inl
src/daemon/rpc_command_executor.cpp
src/serialization/json_object.cpp

Ref: https://github.com/monero-project/monero/pull/5595/commits/2aa11341fc0ae9bcc556ae1a5df7b5cd0ad18e4a

[DAEMON] Display peer address type in print_cn

---

src/daemon/command_line_args.h
src/daemon/daemon.cpp
src/daemon/daemon.h
src/daemon/main.cpp

Ref: https://github.com/monero-project/monero/pull/5597/commits/343c0b4255fc7dcd995ec69399c293f2eb584fb9

[DAEMON-ZMQ] Add a command line option to disable the ZMQ server

---

src/wallet/wallet2.cpp
src/wallet/wallet2.h

Ref: https://github.com/monero-project/monero/pull/5600/commits/dd58057126be2232f2ab59b1b4c18c956ceb20e9

[WALLET] Remember RPC version on initial connect

---

contrib/gitian/README.md
contrib/gitian/gitian-build.py
src/cryptonote_core/tx_sanity_check.cpp
src/p2p/net_node.cpp
src/p2p/net_node.h
src/p2p/net_node.inl
src/rpc/core_rpc_server.cpp
src/rpc/core_rpc_server.h
src/rpc/core_rpc_server_commands_defs.h
src/simplewallet/simplewallet.cpp
tests/difficulty/CMakeLists.txt
tests/unit_tests/mnemonics.cpp
tests/unit_tests/output_selection.cpp
tests/unit_tests/rolling_median.cpp
translations/generate_translations_header.c

Up to upstream https://github.com/monero-project/monero/pull/5635

[MISC] Various fixes/improvements on core, wallet, p2p

---

src/cryptonote_basic/verification_context.h
src/cryptonote_config.h
src/cryptonote_core/blockchain.cpp
src/rpc/core_rpc_server.cpp
src/rpc/core_rpc_server_commands_defs.h
src/rpc/daemon_handler.cpp
src/wallet/wallet2.cpp
tests/functional_tests/transfer.py

Ref: https://github.com/monero-project/monero/commit/df83ed74e487d6f828164bb9652681801abb439e

[CORE] consensus: enforce >= 2 outputs from v9

---

src/common/util.cpp
src/common/util.h
src/cryptonote_core/blockchain.cpp
src/cryptonote_core/blockchain.h
src/daemon/command_parser_executor.cpp
src/daemon/rpc_command_executor.cpp
src/daemon/rpc_command_executor.h
src/rpc/core_rpc_server.cpp
src/rpc/core_rpc_server_commands_defs.h
utils/python-rpc/framework/daemon.py

- Add more chain specific info in alt_chain_info
- Add optional arguments to alt_chain_info
- Sort alt chains by height
Ref: https://github.com/monero-project/monero/pull/5525/commits

[DAEMON] alt_chain_info daemon command usability improvements

---

src/rpc/core_rpc_server.cpp
src/rpc/core_rpc_server.h
src/rpc/core_rpc_server_commands_defs.h

Ref: https://github.com/monero-project/monero/pull/5607/commits/52cd2fa0aff4d6393e91ebb400c33c2449dd1301

[RPC] Implement get_public_nodes command

---

src/cryptonote_core/cryptonote_core.cpp

Ref: https://github.com/monero-project/monero/pull/5637/commits/69f9420489e5dee2b13f29cef47478712aedbb05

[CORE] Not complain about low block rate if disconnected

---

contrib/gitian/README.md
src/p2p/net_peerlist.h

- gitian build README improvements
- p2p: add a reference to Cao, Tong et al. for the last_seen changes

[MISC] Improve README + add contributor reference

---

src/wallet/api/wallet.cpp
src/wallet/api/wallet.h
src/wallet/api/wallet2_api.h

Ref: https://github.com/monero-project/monero/pull/5518/commits/def703abecbd55fdb358b31250bd722766aa24d1

[Wallet API] Add multi destination tx support

---

contrib/depends/packages/icu4c.mk

Ref: https://github.com/monero-project/monero/commit/59eecc7ed15c9c2f55b5529d15c474b0b1526ff1

[DEPENDS] Update icu4c to latest support version

---

contrib/gitian/gitian-linux.yml
contrib/gitian/gitian-osx.yml
contrib/gitian/gitian-win.yml

And updates for sumokoin build
Ref: https://github.com/monero-project/monero/commit/9a5933f705fa8ebc93975e1eb88e1c963cc49ae6

[Gitian] Add version string to output tar archives

---

src/cryptonote_basic/miner.cpp
src/wallet/wallet_args.cpp
tests/unit_tests/blockchain_db.cpp

- wallet: do not print log settings when unset
- unit_tests: check return values on test data parsing
Ref: https://github.com/monero-project/monero/pull/5718/commits

[MISC] Fixes for wallet + unit test

---

src/cryptonote_core/blockchain.cpp
src/cryptonote_core/blockchain.h

which is for tx v1 only
Ref: https://github.com/monero-project/monero/commit/c164f9037ec1d6660c17f737831a9eea29a19cf8

[CORE] Remove unnecessary m_check_txin_table

---

src/rpc/zmq_server.cpp

Ref: https://github.com/monero-project/monero/pull/5725/commits/dc8b7a88bde7467aa15458585eb8f4e2151b63a7

[ZMQ] Fix for MacPorts latest zmq/cppzmq

---

src/rpc/core_rpc_server.cpp
src/rpc/core_rpc_server_commands_defs.h
src/rpc/rpc_handler.cpp

- Add optional extra_nonce for get_block_template
- Work around a GCC 7.4.0 bug

[RPC] Some fixes

---

CMakeLists.txt
README.md

Ref: https://github.com/monero-project/monero/pull/5773/commits/441f318180c402057df3eda278d3df130c31a3f1

[BUILD] Fix building on OpenBSD, simplify Readme section

---

README.md

- Various updates
- Add 'Known Issues' section

[README] Updated

---

src/wallet/wallet2.cpp

Ref: https://github.com/monero-project/monero/pull/5822/commits/839fc6256b7a51c0120a476b592ea780ab97e46b

[Wallet] Reject setting subaddress lookahead major or minor to 0

---

src/simplewallet/simplewallet.cpp

Ref: https://github.com/monero-project/monero/pull/5808/commits

[Wallet] Add missing settings help text

---

src/daemon/rpc_command_executor.cpp
src/p2p/net_node.h
src/p2p/net_node.inl
src/rpc/core_rpc_server.cpp
src/rpc/core_rpc_server_commands_defs.h

Ref: https://github.com/monero-project/monero/commit/fd60d05d5d0c50790f518e7c58f11d73193fc249

[DAEMON] Fix print_pl only printing public zone peers

---

tests/functional_tests/transfer.py

Ref: https://github.com/monero-project/monero/pull/5511/commits/da694d418a7f3152425aa17a7e26c54a20c38283

[TEST] functional_tests: add tests for pending/out transfer addresses

---

src/simplewallet/simplewallet.cpp
src/wallet/wallet2.cpp
src/wallet/wallet2.h

Ref: https://github.com/monero-project/monero/pull/5722/commits/8be5fea1dedfa844afca365d11136e7cc95d5e31

[Simplewallet] Optional all flag to export_outputs/export_key_images

---

external/boost/archive/portable_binary_archive.hpp
external/boost/archive/portable_binary_iarchive.hpp
external/boost/archive/portable_binary_oarchive.hpp
tests/unit_tests/epee_utils.cpp

Ref: https://github.com/monero-project/monero/pull/5748/commits/b350726a5a3b6f9177aa01ec0cbde85c2ac5c5fc

[BOOST] Update obsolete usage of endian API

---

external/easylogging++/easylogging++.cc
external/easylogging++/easylogging++.h

Ref: https://github.com/monero-project/monero/pull/5735/commits/32b0560003b087b9c32407f50bd60eda413d70a2

[Easylogging] Weed out most calls to allowed without locking

---

src/cryptonote_core/tx_sanity_check.cpp

Ref: https://github.com/monero-project/monero/pull/5755/commits/7a3e4588819f8d4667da33f38da2d8f2dfdb0948

[CORE] Improve tx_sanity_check clarification

---

src/cryptonote_protocol/cryptonote_protocol_handler.inl

Ref: https://github.com/monero-project/monero/pull/5815

[P2P] Fix check for disconnecting peers when syncing

---

contrib/epee/include/net/local_ip.h
src/net/parse.cpp

for compatible with older boost versions
Ref: https://github.com/monero-project/monero/commit/30779de39dda848e0e5a8750b38283e146f30132

[BOOST] Fix feature not introduced until boost 1.66

---

src/p2p/net_node.inl

Remove two dead ones -- add three new

Update seed nodes

---

src/cryptonote_protocol/cryptonote_protocol_handler.inl

Added a nice progress bar (2% increments), used a cleaner way to implement the cursor return, added some end-spaces to some messages to flush remaining chars from the cursor return (change is unnoticeable on screen). I love the end result

Improve syncing display. Progress bar and cursor return

---

src/cryptonote_config.h

As average tx size is much smaller after BP implementation

[CORE] Increase block sync count to 50

---

src/cryptonote_protocol/cryptonote_protocol_handler.inl

instread of UTF-8 char so that it can display correctly on
multi platforms (console)

[CORE] Convert sync progress bar to ASCII char

---

src/simplewallet/simplewallet.cpp
src/simplewallet/simplewallet.h
src/wallet/wallet2.cpp
src/wallet/wallet2.h

Ref: https://github.com/monero-project/monero/pull/5416/commits/63186a01ce1603c65771a3ef91f29f3e91679d42

[WALLET] Option to export data to ASCII

---

src/device/device_ledger.cpp
src/device/device_ledger.hpp

Ref: https://github.com/monero-project/monero/pull/5729/commits

[LEDGER] A couple minor fixes found by Coverity

---

Dockerfile
utils/build_scripts/android32.Dockerfile
utils/build_scripts/android64.Dockerfile

Ref: https://github.com/monero-project/monero/pull/5794/commits/a63e212f323918a822d6a8fe1351887caf0fdf47
Ref2: https://github.com/monero-project/monero/pull/5820/commits/ac0a229739c290f593059b9cba23689c94cdec94

[DOCKER] Updated dependencies and fix Android build

---

contrib/epee/include/net/levin_protocol_handler_async.h

in some instances
Ref: https://github.com/monero-project/monero/pull/5824/commits/2a41dc04530e4337a04cee9efc119b82c9ec325e

[Epee] Fix connections not being properly closed

---

contrib/epee/include/console_handler.h
contrib/epee/include/readline_buffer.h
contrib/epee/src/readline_buffer.cpp
src/common/util.cpp
src/common/util.h
src/daemon/main.cpp
src/simplewallet/simplewallet.cpp
src/simplewallet/simplewallet.h
src/wallet/wallet2.cpp
src/wallet/wallet2.h

for obvious security reason
Ref: https://github.com/monero-project/monero/pull/5536/commits/1a367d6a22efc2e596c29d8c3eb95102775f8b24

[Simplewallet] Lock console on inactivity

---

contrib/gitian/gitian-build.py
contrib/gitian/gitian-linux.yml
contrib/gitian/gitian-osx.yml
contrib/gitian/gitian-win.yml

- Change `monero` to `sumokoin` build
- Gitian build (mac, linux): gzip => bzip2
- Gitian build script fixes for MacOS
Ref: https://github.com/monero-project/monero/commit/f26e663a7bc681fceec698e57f2cdcbcfa4a3808

[Gitian] Build fixes

---

src/common/dns_utils.cpp

I guess noone ever tried to create an Openalias address with Sumo otherwise we would have known that this needed fixing... :D  
For future reference if anyone is interested in creating one instructions from monero's official reddit here https://www.reddit.com/r/Monero/comments/2uv214/what_is_openalias/

[DNS_UTILS] Change from Monero to Sumo

---

src/p2p/net_node.inl

Ref: https://github.com/monero-project/monero/pull/5841/commits/cae488dc9b71a21a0ab9608ef8a030d3a422a853

[P2P] Reject incoming connections to self

---

src/simplewallet/simplewallet.cpp

Ref: https://github.com/monero-project/monero/pull/5842/commits/87d2f063af2d1f1b51a82da9af5ea55e0dd364a3

[Simplewallet] Warning harder about untrusted nodes

---

src/wallet/wallet2.cpp

Ref: https://github.com/monero-project/monero/pull/5850/commits/c4da1a25c39f8412a2e9a5362b4752b9bde44ca5

[Wallet] Fix unset_ring tx retrieval checks

---

src/cryptonote_core/blockchain.cpp
src/simplewallet/simplewallet.cpp

- Simplewallet: fix warnings about useless std::move
- Blockchain: fix logging bad number of blocks if first one fails

[Core] Fix warnings

---

contrib/epee/include/int-util.h
contrib/epee/include/net/local_ip.h
contrib/epee/include/net/net_utils_base.h
contrib/epee/include/storages/portable_storage_bin_utils.h
contrib/epee/include/storages/portable_storage_from_bin.h
contrib/epee/include/storages/portable_storage_to_bin.h
external/boost/archive/portable_binary_iarchive.hpp
external/boost/archive/portable_binary_oarchive.hpp
src/blockchain_db/lmdb/db_lmdb.cpp
src/crypto/cn_monero_slow_hash.c
src/p2p/net_peerlist_boost_serialization.h
tests/unit_tests/difficulty.cpp
tests/unit_tests/epee_levin_protocol_handler_async.cpp

Ref: https://github.com/monero-project/monero/pull/5544

[ALL] Big endian fixes

---

src/daemon/command_parser_executor.cpp
src/daemon/rpc_command_executor.cpp
src/daemon/rpc_command_executor.h

- Also, fix merge error removing the "never seen before" timestamp check

[Daemon] Add pruned and publicrpc flags to print_pl

---

src/device/device_ledger.cpp

Ref: https://github.com/monero-project/monero/pull/5835/commits/26f7a26ee3f53008b2b49a760464199d2631e2a8

[Device] Fix ledger requesting secret keys export twice

---

src/blockchain_utilities/blockchain_blackball.cpp
src/wallet/ringdb.cpp

which prints historical stats of spent ratio

[Utilities] blockchain_blackball: add --historical-stat

---

src/wallet/wallet2.cpp

Ref: https://github.com/monero-project/monero/pull/5847/commits/894cc81e835848a42b24c2a3efaf7261f170cf2c

[Wallet] Fix cold signing losing tx keys

---

src/cryptonote_protocol/cryptonote_protocol_handler.inl

When syncing is complete get it printed one line below so it doesnt cover the progress bar

[DAEMON] Vanity fix

---

src/daemon/core.h

[DAEMON] ASCII

---

src/wallet/api/subaddress_account.cpp
src/wallet/api/wallet.cpp

Ref: https://github.com/monero-project/monero/pull/5899/commits/7d3bba5ca0e30f199efbbdf89f7243588bdf1459

[Wallet API] Add 'balance' missing parameters

---

src/wallet/wallet2.cpp

Ref: https://github.com/monero-project/monero/pull/5861/commits/acaadd13dc0a07ffe7c560ac8457f005ea717dbb

[Wallet] Enable ignoring fractional outputs also when sweeping

---

src/simplewallet/simplewallet.cpp

Improvement of the ASCII SUMOKOIN art plus a nice typewriter text effect upon wallet locking. 
Please check on your display as well for any ascii space screw ups before merging on mine it seems fine

[SIMPLEWALLET] Better wallet lock screen

---

src/rpc/core_rpc_server_commands_defs.h
src/wallet/wallet2.cpp
src/wallet/wallet_light_rpc.h

Ref: https://github.com/monero-project/monero/pull/5866/commits/21f6c80fcd7de27245d529edf383e3196c12f847

[RPC] Move a leftover light wallet RPC out of daemon RPC

---

src/cryptonote_core/cryptonote_core.cpp

Ref: https://github.com/monero-project/monero/pull/5854/commits/2cb22d407113f119ba22219113e2cee2440fee30

[CORE] Make core update message less scary

---

src/daemon/rpc_command_executor.cpp

Ref: https://github.com/monero-project/monero/pull/5868/commits/1f1fff26790eb2ef998287a3519bbb2f7981d808

[DAEMON] Print mining algo in mining_status even when not mining

---

contrib/epee/include/net/abstract_tcp_server2.inl

Ref: https://github.com/monero-project/monero/pull/5898/commits/73f22c48e1fe923ff0d896b6e632c4f232f5f754

[Depends] Fix MacOS build with Clang 3.7.1

---

contrib/epee/include/misc_log_ex.h
contrib/epee/src/mlog.cpp

to be used in the randomx integration code
Ref: https://github.com/monero-project/monero/pull/5909/commits/8277c7e0dda0c49d5935b242ce98f8c465a18ea6

[EPEE] misc_log_ex.h can now be used in C code

---

src/blockchain_db/blockchain_db.h
src/cryptonote_core/blockchain.cpp
src/cryptonote_core/tx_pool.cpp
src/cryptonote_core/tx_pool.h

Ref: https://github.com/monero-project/monero/pull/5919/commits/bcbc46bf03e126437fd2f5621a4621c692d6a320

[Blockchain] Fill in cumulative block weight for alt blocks

---

contrib/epee/include/misc_log_ex.h
contrib/epee/src/mlog.cpp
external/easylogging++/easylogging++.cc
external/easylogging++/easylogging++.h
src/common/perf_timer.cpp
src/cryptonote_core/cryptonote_core.cpp
src/cryptonote_protocol/cryptonote_protocol_handler.inl
tests/unit_tests/logging.cpp

Colouring on Windows should now work regardless of version

[LOGGING] Properly format multiline logs

---

contrib/lsan/lsan.supp

with the Cryptonight per-thread buffer

[Contrib] Add a suppressions file for leak sanitizer

---

tests/unit_tests/multiexp.cpp
tests/unit_tests/ringdb.cpp

Fixes assertion failure (curstate == 1) in random.c in debug mode

[Unit test]: Replace global var with lambda returning static local var

---

src/cryptonote_core/blockchain.cpp

Use the lesser of the short and long terms medians, rather then
the long term median alone

[Blockchain] Tweak fee as a function of median values

---

contrib/epee/include/net/net_helper.h

Ref: https://github.com/monero-project/monero/pull/5917/commits/7d81850a4619c03b1d0e16183a7ee311c428d849

[EPEE] Fix network timeouts in blocked_mode_client

---

contrib/epee/include/net/net_helper.h
contrib/epee/include/net/net_ssl.h
contrib/epee/src/net_ssl.cpp

Ref: https://github.com/monero-project/monero/pull/5918/commits/4371791977a18653da16a99f41de46cee5fa337b

[EPEE] Implement handshake timeout for SSL connections

---

src/cryptonote_protocol/levin_notify.cpp
src/cryptonote_protocol/levin_notify.h
src/p2p/net_node.inl
tests/unit_tests/levin.cpp

Ref: https://github.com/monero-project/monero/pull/5921/commits/2a7d91523bbe24d87d6e957592f13f46d62595ce

[I2P/TOR] Fixed i2p/tor tx flooding bug (white noise disabled)

---

src/cryptonote_core/cryptonote_core.cpp
src/cryptonote_core/cryptonote_core.h

Been there since the beginning was never used and most probably never will
Ref https://github.com/loki-project/loki/commit/c2f2c8306ebc82c72fa8680f3b248c758e7df5ad

[CORE] Remove method that is not used

---

src/wallet/wallet_rpc_server.cpp

[WALLET RPC] Change monero to sumokoin

---

external/easylogging++/ea_config.h

Merge this first cause with the current commits branch wont build
https://github.com/monero-project/monero/commit/080ea734c2c6da5a3b90cb25a383df53a44168cd

Important! Easylogging++: fix build with glibc

---

src/daemon/rpc_command_executor.cpp

Monero, like we did, has moved the hardfork code part out of blockchain.cpp to a seperate file with its own header (like checkpoints), @quangvu3 please check when you set up the coming hardfork if the countdown still shows on status message, i havent checked if they've changed the variable names, i used the same string. If it doesnt we will remove the part counting down for the next release (Next hardfork:) and fix it

[DAEMON] Update status call

---

src/cryptonote_core/cryptonote_core.cpp
src/cryptonote_core/cryptonote_core.h
src/cryptonote_protocol/cryptonote_protocol_handler.inl

When on idle, fully synced and everything is ok pop a msg every 30 mins  including a few details (current height and uptime) so we now everything is ok without having to type status or anything else

[CORE] Pop periodical ok msg

---

src/simplewallet/simplewallet.cpp
src/simplewallet/simplewallet.h
src/wallet/wallet2.cpp
src/wallet/wallet2.h
src/wallet/wallet_rpc_server.cpp
tests/functional_tests/cold_signing.py
tests/functional_tests/multisig.py
tests/functional_tests/transfer.py

since fork v9
Ref: https://github.com/monero-project/monero/pull/5834

[WALLET] Remove long payment ID support

---

src/cryptonote_basic/verification_context.h
src/cryptonote_core/blockchain.cpp
src/cryptonote_protocol/cryptonote_protocol_handler.h
src/cryptonote_protocol/cryptonote_protocol_handler.inl
src/p2p/net_node.h
src/p2p/net_node.inl
src/p2p/net_node_common.h
src/rpc/core_rpc_server.cpp
src/rpc/core_rpc_server.h

PoW is expensive to verify, so be strict

[Protocol] Ban peers sending bad pow outright

---

src/wallet/wallet_rpc_server.cpp

on_transfer_split error consistent with on_transfer if no tx sent

[RPC] Fix inconsistant error at on_transfer_split

---

contrib/epee/include/net/abstract_tcp_server2.inl

Ref https://github.com/loki-project/loki/commit/7568fb9d1e58a85000b8c96eda630d59545fe641

[EPEE] Fix type ambiguity in epee

---

src/daemon/rpc_command_executor.cpp
src/rpc/core_rpc_server.cpp

and don't serialize miner tx hash twice in print_block

[RPC] Print cumulative difficulty

---

src/simplewallet/simplewallet.cpp

since they're all locked for a fixed amount

[Simplewallet] Do not print warning for locked coinbase txes

---

src/daemon/rpc_command_executor.cpp

It got switched to hexadecimal when we went to 128 bit values

[Daemon] Print difficulty in decimal

---

src/blockchain_utilities/CMakeLists.txt
src/blockchain_utilities/utilities_menu.cpp

@quangvu3 amended as per your suggestions

[Blockchain Utilities] Utilities menu

---

cmake/GitVersion.cmake
cmake/Version.cmake

- Also, allow build out of source

[CMake] Fix generation of version.cpp

---

src/cryptonote_core/cryptonote_tx_utils.cpp
src/device/device_ledger.cpp
src/device/device_ledger.hpp

[LEDGER] app 1.4: protocol fix + address display

---

src/cryptonote_basic/miner.cpp
src/cryptonote_basic/miner.h
src/cryptonote_core/cryptonote_core.cpp
src/cryptonote_core/cryptonote_tx_utils.cpp
src/rpc/core_rpc_server.cpp
tests/core_tests/chaingen.cpp

that causes link errors at least on mac

[CORE] Untangle dependency from miner to blockchain

---

src/rpc/core_rpc_server.cpp
src/rpc/rpc_payment.cpp
src/wallet/wallet_rpc_payments.cpp

Code should be at RandomX branch instead

[MISC] Remove TODO randomx comment-outs

---

src/blockchain_utilities/utilities_menu.cpp

since ansi codes are not working properly on windows

Give the utilities menu some colour with scoped message writer

---

contrib/depends/toolchain.cmake.in

[Depends] CMake: cache THREADS_PTHREAD_ARG

---

src/blockchain_utilities/utilities_menu.cpp

As it cause error at cross-build

Revert "Give the utilities menu some colour with scoped message writer"

---

src/rpc/core_rpc_server.cpp

We would be getting "I am not sure actually" on status :D

[RPC] fix res pow algo case

---

contrib/gitian/gitian-android.yml
contrib/gitian/gitian-build.py
contrib/gitian/gitian-linux.yml
contrib/gitian/gitian-osx.yml
contrib/gitian/gitian-win.yml

Ref: https://github.com/monero-project/monero/pull/6091/commits/5b78c27c5023764205d51194be9902d00dbe4886

[Gitian] Copy LICENSE to all archives and correct version/path

---

src/cryptonote_core/tx_pool.cpp
src/cryptonote_core/tx_sanity_check.cpp
src/wallet/wallet2.cpp

that only set for half after BP applied
- And losen sanity check for `unique indices` at sumokoin

[Wallet] Fix tx weight limit

---

src/blockchain_utilities/CMakeLists.txt

like `sumo-blockchain-import`, `sumo-blockchain-export` ...

[BLOCKCHAIN UTILS] Fix backcompat for blockchain utilities

---

src/ringct/bulletproofs.cc

Slightly more efficient computation of scalars used by Bulletproofs prover

[Bulletproofs] Updated paper references + minor prover simplification

---

src/wallet/wallet2.cpp
src/wallet/wallet2.h

protects against having your keys mangled

[Wallet2] Make keys unlocker reentrant

---

utils/python-rpc/framework/daemon.py
utils/python-rpc/framework/wallet.py

- Add missing strict_balances parameter for get_accounts
- Add missing closing bracket

[python-rpc] Some fixes

---

src/wallet/wallet2.cpp

As per https://github.com/monero-project/monero/pull/6235 fix

[WALLET] fix hang in wallet refresh

---

README.md
src/simplewallet/simplewallet.cpp

[README] small trivial fix from monero to sumo

---

src/crypto/cn_heavy_hash.hpp

... with the rest of environment flags

Change the flag's name to be consistent

---

src/common/threadpool.cpp
src/common/threadpool.h
tests/core_tests/chaingen.h

Ref: https://github.com/monero-project/monero/pull/6115

[core_tests] reset thread pool between tests

---

contrib/epee/include/string_tools.h

Ref: https://github.com/monero-project/monero/pull/6120

[EPEE] fix peer ids being truncated on display

---

src/cryptonote_core/blockchain.cpp

Ref: https://github.com/monero-project/monero/pull/6124

[Blockchain] error out if the builtin hashes data size is wrong

---

utils/translations/build-translations.sh

Ref: https://github.com/monero-project/monero/pull/6139

[translations] fix qt5 lrelease and missing prefix

---

contrib/epee/include/net/http_server_handlers_map2.h

Ref: https://github.com/monero-project/monero/pull/6143

[EPEE] set application/json MIME type on json errors

---

src/p2p/net_node.inl

Ref: https://github.com/monero-project/monero/pull/6153

[P2P] don't request flags after closing connection

---

src/wallet/wallet2.cpp

Ref: https://github.com/monero-project/monero/pull/6154

[wallet2] don't issue node rpc proxy requests in '--offline' mode

---

src/rpc/core_rpc_server.cpp
src/rpc/core_rpc_server_commands_defs.h

Ref: https://github.com/monero-project/monero/pull/6172

[RPC] add received_timestamp for pool txes in gettransactions

---

src/rpc/core_rpc_server.cpp

- Fix bootstrap RPC payment RPC being made in raw JSON, not JSON RPC

[RPC] Fix daemon bootstrap mode with a daemon requiring payment

---

Makefile

Ref: https://github.com/monero-project/monero/pull/6267

[MSYS2] autodetect MSYS2 install path, support non-standard location

---

src/simplewallet/simplewallet.cpp
src/wallet/api/address_book.cpp
src/wallet/wallet2.cpp
src/wallet/wallet2.h
src/wallet/wallet_rpc_server.cpp
src/wallet/wallet_rpc_server_commands_defs.h
tests/functional_tests/address_book.py
tests/unit_tests/serialization.cpp

Ref: https://github.com/monero-project/monero/pull/6158

[wallet] do not split integrated addresses in address book api

---

contrib/epee/include/storages/levin_abstract_invoke2.h
src/blockchain_db/blockchain_db.cpp
src/blockchain_db/blockchain_db.h
src/cryptonote_config.h
src/cryptonote_core/cryptonote_core.cpp
src/cryptonote_core/cryptonote_core.h
src/cryptonote_protocol/cryptonote_protocol_handler.inl
src/cryptonote_protocol/enums.h
src/cryptonote_protocol/levin_notify.cpp
src/cryptonote_protocol/levin_notify.h
src/p2p/net_node.cpp
src/p2p/net_node.h
src/p2p/net_node.inl
src/p2p/net_node_common.h
tests/core_tests/chaingen.h
tests/net_load_tests/clt.cpp
tests/net_load_tests/net_load_tests.h
tests/net_load_tests/srv.cpp
tests/unit_tests/levin.cpp
utils/logs/levin-traffic.awk

Ref: https://github.com/monero-project/monero/pull/6170
Steps on : https://github.com/sumoprojects/sumokoin/pull/647

[Network] log traffic and add a simple traffic analysis script

---

src/blockchain_db/blockchain_db.h
src/blockchain_db/lmdb/db_lmdb.cpp
src/blockchain_db/lmdb/db_lmdb.h
src/blockchain_db/testdb.h
src/cryptonote_core/blockchain.cpp

[Blockchain] Speedup fetching pruned contiguous tx blobs

---

ANDROID-BUILD.md

[Android branch] Fix a command on instructions

---

src/blockchain_utilities/utilities_menu.cpp
src/cryptonote_protocol/cryptonote_protocol_handler.inl
src/daemon/rpc_command_executor.cpp
src/p2p/net_node.inl
src/p2p/p2p_protocol_defs.h

and [Deamon RPC] Update print_connections result format
Ref: monero-project/monero@deb350b

[ALL] Fix peer ID format consistancy

---

src/cryptonote_core/blockchain.cpp

Ref: https://github.com/monero-project/monero/commit/d7aeb5a9f86442b5ac4464896cc7d8eb2740dadb

[blockchain] fix flushing txes from the txpool

---

src/rpc/core_rpc_server.cpp
src/rpc/rpc_payment.cpp
src/wallet/node_rpc_proxy.cpp
tests/functional_tests/make_test_signature.cc

Ref: https://github.com/monero-project/monero/pull/6035
Multiple separate commits as per above pr for better tracking

Misc fixes found by coverity on recent code

---

src/rpc/core_rpc_server_commands_defs.h

Ref: https://github.com/monero-project/monero/pull/6040

[rpc] base flush_cache request/response on the new base structs

---

src/cryptonote_core/cryptonote_core.cpp

Ref: https://github.com/monero-project/monero/pull/6050

[core] point out when we hit the block rate visibility limit

---

src/simplewallet/simplewallet.cpp
src/wallet/wallet2.cpp
src/wallet/wallet2.h
src/wallet/wallet_rpc_server.cpp
src/wallet/wallet_rpc_server_commands_defs.h
tests/functional_tests/sign_message.py
utils/python-rpc/framework/wallet.py

Ref: https://github.com/monero-project/monero/pull/6069

[wallet] allow message sign/verify for subaddresses

---

src/cryptonote_core/cryptonote_core.cpp

ref: https://github.com/monero-project/monero/pull/6078

[core] Add a --keep-fakechain option to keep fakechain databases

---

src/blockchain_utilities/blockchain_stats.cpp

Ref: https://github.com/monero-project/monero/pull/6094

[utilities] make blockchain_stats work on pruned chains

---

src/daemon/command_parser_executor.cpp
src/daemon/rpc_command_executor.cpp
src/daemon/rpc_command_executor.h

Ref: https://github.com/monero-project/monero/pull/6096

[daemon] allow printing N blocks from the end of the chain

---

src/wallet/wallet2.cpp

Ref: https://github.com/monero-project/monero/pull/6103

[wallet2] don't try to lock an empty filename

---

contrib/epee/include/net/net_helper.h
contrib/epee/src/http_auth.cpp

Ref: https://github.com/monero-project/monero/pull/6182

[epee] reorder a couple init list fields to match declaration

---

src/common/download.cpp

Ref: https://github.com/monero-project/monero/pull/6183

[download] catch exceptions checking for size

---

README.md

Due to official site change links became obsolete (grab from imgur now to avoid such issues)

[readme] Add missing emission charts (plus updates)

---

utils/systemd/sumokoind.service

[systemd] change from monero to sumokoin service

---

contrib/depends/Makefile

This address doesnot even exist anymore

[depends] Remove obsolete fallback address

---

src/daemon/command_parser_executor.cpp
src/daemon/command_parser_executor.h
src/daemon/command_server.cpp
src/daemon/rpc_command_executor.cpp
src/daemon/rpc_command_executor.h

Based on @quangvu3 's cpp version of Sumokoin's emission scheme emulation to create a daemon command that prints the emission scheme along with the current height.

[daemon] new command 'print_emission'

---

src/daemon/rpc_command_executor.cpp

[daemon] add remote height on print_cn command

---

src/simplewallet/simplewallet.cpp

From the previous mess to this

[simplewallet] make show_transfers user friendly

---

src/daemon/rpc_command_executor.cpp

This it the last thing I m adding and i m not touching that command again :)
Print next to each connection if it's an open node accepting remote wallet connections along with their open RPC port

[daemon] print_cn command update

---

src/wallet/wallet2.cpp
src/wallet/wallet2.h
src/wallet/wallet_rpc_server.cpp
src/wallet/wallet_rpc_server_commands_defs.h

Ref: https://github.com/monero-project/monero/pull/6190

[wallet2] Distingush amounts for a single subaddress

---

src/simplewallet/simplewallet.cpp

Ref: https://github.com/monero-project/monero/pull/6197

[simplewallet] fix encrypted payment id notification not to trigger on dummy ones

---

src/daemon/daemon.cpp
src/daemon/rpc.h
src/rpc/core_rpc_server.cpp
src/rpc/core_rpc_server.h

Ref: https://github.com/monero-project/monero/pull/6198

[daemon] run with --rpc-payment-address and --rpc-restricted-bind-port

---

src/crypto/chacha.h
src/crypto/hash-ops.h
src/crypto/hash.h
src/cryptonote_basic/cryptonote_format_utils.cpp
src/wallet/wallet_rpc_payments.cpp

~~Dont merge yet~~
It can be merged. Thanks!

[android wallet branch] amend slow hash for keys/password hashing

---

README.md

Partial ref: https://github.com/monero-project/monero/pull/6204

[Readme] Android (32&64bit) cross compiling instr.

---

src/daemon/rpc_command_executor.cpp

ref my pr : https://github.com/monero-project/monero/pull/6353

[daemon] Print something if no bans

---

contrib/epee/src/net_ssl.cpp

Ref: https://github.com/monero-project/monero/pull/6205

[SSL] allow multiple version of TLS

---

src/rpc/core_rpc_server.cpp
src/rpc/core_rpc_server.h
src/rpc/rpc_args.cpp
src/rpc/rpc_args.h

Ref: https://github.com/monero-project/monero/pull/6215

[RPC] Command line option to disable ban RPC clients

---

contrib/epee/include/serialization/keyvalue_serialization_overloads.h
contrib/epee/include/storages/parserse_base_utils.h
contrib/epee/include/storages/portable_storage.h
contrib/epee/include/storages/portable_storage_base.h
contrib/epee/include/storages/portable_storage_from_bin.h
contrib/epee/include/storages/portable_storage_from_json.h
tests/unit_tests/net.cpp

Ref: https://github.com/monero-project/monero/pull/6220
This improves serialization/deserialization speed quite a bit which in turn improves performance of the p2p code

[epee] Improved performance for epee serialization

---

src/simplewallet/simplewallet.cpp

Ref: https://github.com/monero-project/monero/pull/6224

[simplewallet] warn on refresh if refresh-from-block-height seems off

---

src/wallet/wallet2.cpp

Ref: https://github.com/monero-project/monero/pull/6296

[Wallet2] reject zero keys in json input

---

src/simplewallet/simplewallet.cpp

Ref: https://github.com/monero-project/monero/pull/6222

[simplewallet] set manual refresh mode in rescan_bc

---

src/wallet/wallet2.cpp
src/wallet/wallet2.h

Ref: https://github.com/monero-project/monero/pull/6238

[wallet2] guard against race with multiple decrypt_keys users

---

src/p2p/net_node.inl

Ref: https://github.com/monero-project/monero/pull/6248

[p2p] drop the peerlist dump to TRACE

---

contrib/epee/include/net/net_utils_base.h
contrib/epee/include/serialization/keyvalue_serialization.h
src/cryptonote_protocol/cryptonote_protocol_defs.h
src/p2p/net_node.h
src/p2p/net_node.inl
src/p2p/net_peerlist.h
src/p2p/p2p_protocol_defs.h
tests/functional_tests/transfer.py

Ref: https://github.com/monero-project/monero/pull/6243
bandwidth savings :) ....

[p2p] bandwidth savings

---

src/rpc/message.cpp
tests/unit_tests/CMakeLists.txt
tests/unit_tests/zmq_rpc.cpp

Ref: https://github.com/monero-project/monero/pull/6362
(as merged by luigi1111 on xmr's 0.15 branch for their upcoming release. If there are amendments when this is merged on xmr's master they will be included)

[zmq rpc] Fixed bug in ZMQ JSON-RPC method field

---

src/simplewallet/simplewallet.cpp
src/wallet/wallet2.cpp
src/wallet/wallet2.h
src/wallet/wallet_rpc_server.cpp

Ref: https://github.com/monero-project/monero/pull/6365
(as merged by luigi1111 on xmr's 0.15 branch for their upcoming release. If there are amendments when this is merged on xmr's master (https://github.com/monero-project/monero/pull/6268) they will be included)

[wallet] fix exceptions getting the hash of a pruned tx

---

src/p2p/net_node.inl

Ref: https://github.com/monero-project/monero/pull/6373
(as merged by luigi1111 on xmr's 0.15 branch for their upcoming release. If there are amendments when this is merged on xmr's master https://github.com/monero-project/monero/pull/6372 they will be included)

[p2p] plug tor to clearnet association vector

---

src/cryptonote_protocol/levin_notify.cpp

I am bringing in this https://github.com/monero-project/monero/pull/6375 which is still open on master and not this https://github.com/monero-project/monero/pull/6376 merged on their 15.1 coming release cause there are differences due to changes applied on master after 15.0 release. There is divergence between their current master branch and the upcoming 15.1 branch on dandelion, levin protocol and cryptonote protocol parts. I dont understand why they decided to complicate things that much, I really hope they checked for any conflicts cause people will be running user compiled builds from master and 15.1 released builds at the same time

[i2p] Added logging for dropped local txes with no i2p/tor connections

---

contrib/gitian/README.md
contrib/gitian/gitian-build.py

Ref: https://github.com/monero-project/monero/pull/6263
We currently dont support gitian builds but keep it updated in case we change our mind in the future

[gitian] Change lxc ip link

---

contrib/depends/packages/qt.mk

Ref mine: https://github.com/monero-project/monero/pull/6398

[depends] update qt 5.7.1 download link

---

src/p2p/net_node.inl

Ref: https://github.com/monero-project/monero/pull/6280

[p2p] fix spurious warning when we're connected to at last one seed

---

src/p2p/net_node.inl

Ref: https://github.com/monero-project/monero/pull/6279

[p2p] fix adding wrong indices to the filtered peer list

---

src/blockchain_db/locked_txn.h
src/cryptonote_core/tx_pool.cpp

Ref: https://github.com/monero-project/monero/pull/6227

[core] move the LockedTXN class out of txpool so it may be reused

---

src/cryptonote_protocol/cryptonote_protocol_handler.inl

Ref: https://github.com/monero-project/monero/pull/6282

[daemon] guard against reporting synchronized too early

---

src/cryptonote_core/blockchain.cpp

Ref: https://github.com/monero-project/monero/pull/6284
Adjusted for sumo
@quangvu3 please check if it is compatible with https://github.com/sumoprojects/sumokoin/pull/570

[core] fix check_fee() and get_dynamic_base_fee_estimate() discrepancies

---

src/wallet/api/wallet.cpp
src/wallet/api/wallet.h
src/wallet/api/wallet2_api.h
src/wallet/wallet2.cpp
src/wallet/wallet2.h

Ref: https://github.com/monero-project/monero/pull/6302
**Fork rules adjusted for Sumo please check**

[wallet2_api] implement estimateTransactionFee

---

src/wallet/wallet2.cpp
src/wallet/wallet2.h

Ref: https://github.com/monero-project/monero/pull/6299

[wallet2] remember daemon address overrides when loading a new wallet

---

src/p2p/net_node.h
src/p2p/net_node.inl
src/p2p/net_peerlist.h

Ref: https://github.com/monero-project/monero/pull/6295

[p2p] do not add recently failed addresses to the peerlist

---

contrib/gitian/gitian-build.py

Ref: https://github.com/monero-project/monero/pull/6290
(TODO: we fully support gitian builds, we need a gitian.sigs repo to store files asserting the signed, reproducible builds from contributors along with their pgp public keys. Not urgent but nice to have in the future)

[gitian-building] Fixing check for docker command

---

contrib/epee/include/storages/portable_storage_base.h

Ref: https://github.com/monero-project/monero/pull/6311

[epee] Explicitly define copy assignment operator

---

src/rpc/core_rpc_server.cpp

Ref: https://github.com/monero-project/monero/pull/6325

[RPC] Fix print_pool_sh not finding local txes

---

contrib/epee/include/console_handler.h
src/common/threadpool.cpp
src/cryptonote_core/tx_pool.cpp

Ref: https://github.com/monero-project/monero/pull/6336
Minor fixes found by running coverity analysis tool on monero
Left the commits separate as mooo's for reference

[coverity] minor fixes from coverity

---

contrib/epee/include/net/levin_protocol_handler_async.h
src/p2p/net_node.inl

Ref: https://github.com/monero-project/monero/pull/6269

[p2p] fix frequent weak_ptr exception on connection

---

tests/functional_tests/make_test_signature.cc
tests/functional_tests/rpc_payment.py

Ref: https://github.com/monero-project/monero/pull/6309

[tests] fix rpc payment tests spurious failure and speedup signature generation

---

src/wallet/wallet2.cpp

Ref: https://github.com/monero-project/monero/pull/6321

[wallet2] mention --daemon-ssl-allow-any-cert in --proxy error msg

---

src/device/device_ledger.cpp
src/device/device_ledger.hpp

Ref: https://github.com/monero-project/monero/pull/6322

[device_ledger] include status code name in error message

---

src/cryptonote_core/cryptonote_core.cpp

Ref: https://github.com/monero-project/monero/pull/6328

[core] mention time being off in hash rate changes message

---

src/wallet/api/wallet.cpp
src/wallet/api/wallet.h
src/wallet/api/wallet2_api.h
src/wallet/api/wallet_manager.cpp
src/wallet/api/wallet_manager.h

Ref: https://github.com/monero-project/monero/pull/6334

[wallet2_api] wallet recovery - seed offset passphrase support

---

contrib/epee/demo/iface/transport_defs.h
contrib/epee/include/net/http_protocol_handler.h
contrib/epee/include/net/munin_connection_handler.h
src/blockchain_db/lmdb/db_lmdb.cpp
src/cryptonote_config.h
src/cryptonote_core/blockchain.cpp
src/cryptonote_core/cryptonote_tx_utils.cpp
src/daemon/main.cpp
src/ringct/bulletproofs.cc
src/simplewallet/simplewallet.cpp
tests/unit_tests/mul_div.cpp
tests/unit_tests/test_tx_utils.cpp

Some double semi colons removal as per https://github.com/monero-project/monero/pull/6339 (empty statements they're called they do nothing and most likely the second ; got there by mistake)
and to please my compulsive disorder i lined up cryptonote_config.h variables

code clean up

---

src/rpc/rpc_payment_signature.cpp

Ref: https://github.com/monero-project/monero/pull/6342

[rpc] add check for too old timestamps in payment signatures

---

tests/unit_tests/hmac_keccak.cpp
tests/unit_tests/keccak.cpp

Ref: https://github.com/monero-project/monero/pull/6346

[tests] unit_tests: fix missing test names

---

README.md

And delete a line that doesnot apply in sumo
Partialy based on https://github.com/monero-project/monero/pull/6356

[README] Provides safer semaphore privilege to FreeBSD jail

---

src/cryptonote_core/blockchain.cpp
src/cryptonote_core/blockchain.h

Ref: https://github.com/monero-project/monero/pull/6347

[cryptonote_core] skip block notify on blockchain switching rollback

---

src/device/device_io_hid.cpp

Ref: https://github.com/monero-project/monero/pull/6364

[device] ledger - fix wide char hidapi error string conversion

---

contrib/epee/src/net_ssl.cpp

Ref: https://github.com/monero-project/monero/pull/6387

[epee] avoid spamming 'Generating SSL certificate' in the logs

---

src/simplewallet/simplewallet.cpp

Ref: https://github.com/monero-project/monero/pull/6440
(mine)

[simplewallet] fix strings (show_transfers & export_transfers)

---

utils/conf/sumokoind.conf

[utils] sumokoind configuration (xmr to sumo)

---

src/blockchain_db/blockchain_db.h
src/blockchain_db/lmdb/db_lmdb.cpp
src/blockchain_db/lmdb/db_lmdb.h
src/blockchain_db/testdb.h
src/cryptonote_core/blockchain.cpp

Ref: https://github.com/monero-project/monero/pull/6358
Another one of mooo's great ones, majorly improving wallet rescan by cutting down more than 1/3 of the time needed for it to complete!
Along with vtnerd's SuperCop ASM (when merged) wallet rescan will really fly
Node sync speed is improved as well!

[blockchain_db] faster fetching of consecutive txes

---

src/cryptonote_core/tx_pool.cpp
tests/core_tests/chaingen_main.cpp
tests/core_tests/tx_pool.cpp
tests/core_tests/tx_pool.h

Ref: https://github.com/monero-project/monero/pull/6403
Dandelion++ will either be one of the best features of Monero or one of their biggest flops... 
There is no middle road about it ....

[dandelion++] correct key image check in tx_pool

---

src/simplewallet/simplewallet.cpp
src/simplewallet/simplewallet.h

Sweep entirely a selected wallet account

[simplewallet] create sweep_account command

---

src/blockchain_db/lmdb/db_lmdb.cpp

and warn us hard if it is below 4 Gb
Pushed same to Monero (waiting for review)

[lmdb] print available disk space after each db resize

---

src/daemon/rpc_command_executor.cpp

Ref: https://github.com/monero-project/monero/pull/6408

[daemon] fix print_net_stats rpc calls

---

src/simplewallet/simplewallet.cpp

image is from rescan_bc same print output on receive or send

[simplewallet] print in better format inc and out tx details

---

src/simplewallet/simplewallet.cpp

For some reason a draft version of this https://github.com/sumoprojects/sumokoin/pull/861 got through
This fixes it

[simplewallet] fix inc and out txs display

---

src/cryptonote_basic/cryptonote_format_utils.cpp
src/cryptonote_basic/cryptonote_format_utils.h
src/cryptonote_core/cryptonote_tx_utils.cpp
src/device/device.hpp
src/device/device_default.cpp
src/device/device_default.hpp
src/device/device_ledger.cpp
src/device/device_ledger.hpp

Ref: https://github.com/monero-project/monero/pull/6436
Bringing this in for code consistency only

[device] add timelock verification

---

src/simplewallet/simplewallet.cpp
src/simplewallet/simplewallet.h
src/wallet/wallet2.cpp
src/wallet/wallet2.h

[wallet2] fix unlock keys with password when tx is found in pool

---

src/crypto/crypto.cpp
src/multisig/multisig.cpp
src/ringct/rctSigs.cpp
src/ringct/rctTypes.h
src/wallet/wallet2.cpp

[crypto] use memwipe on secret k/alpha values

---

src/wallet/wallet2.cpp

[wallet2] check_connection return false on get_version status != OK

---

src/rpc/core_rpc_server.cpp

[rpc] fix 'use_bootstrap_daemon_if_necessary' return value

---

src/simplewallet/simplewallet.cpp
src/wallet/wallet2.cpp
src/wallet/wallet2.h
src/wallet/wallet_rpc_server.cpp
src/wallet/wallet_rpc_server_commands_defs.h

[simplewallet] report timestamp based expected unlock time on balance

---

.github/workflows/build.yml

[workflows] msys2 pacman update bug workaround

---

src/simplewallet/simplewallet.cpp
src/simplewallet/simplewallet.h
src/wallet/api/wallet.cpp
src/wallet/wallet2.cpp
src/wallet/wallet2.h

Ref Monero #6527
I can think of a couple of nice things to do with this that they added

[simplewallet] don't complain about incoming payment ids on change

---

contrib/epee/include/md5_l.inl

[epee] use memwipe rather than memset for md5 secrets

---

external/easylogging++/easylogging++.cc
src/common/CMakeLists.txt
src/common/utf8.h
src/mnemonics/language_base.h

[easylogging++] sanitize log payload

---

src/cryptonote_core/cryptonote_core.cpp
src/cryptonote_protocol/cryptonote_protocol_handler.inl
src/simplewallet/simplewallet.cpp
src/simplewallet/simplewallet.h

Ref Monero #6541
They say it was breaking existing help command behaviour and they will go for something better in the near future

[simplewallet] revert noob-friendly help menu

---

src/serialization/json_object.cpp

[serialization] fix bad rapidjson api usage

---

src/wallet/wallet2.cpp

[wallet2] fix multisig data clearing stomping on a vector

---

src/cryptonote_protocol/cryptonote_protocol_handler.inl

[protocol] move the "peer claims higher version" warning to debug

---

src/cryptonote_protocol/cryptonote_protocol_handler.inl

Ref Monero #6554
Pretty useless but anyhow i port it
I left out the change on src/cryptonote_protocol/cryptonote_protocol_handler.h  which is rubbish 
```
- #define CURRENCY_PROTOCOL_MAX_OBJECT_REQUEST_COUNT 500
+ #define CURRENCY_PROTOCOL_MAX_OBJECT_REQUEST_COUNT 100
+ static_assert(CURRENCY_PROTOCOL_MAX_OBJECT_REQUEST_COUNT >= BLOCKS_SYNCHRONIZING_DEFAULT_COUNT_PRE_V4, "Invalid CURRENCY_PROTOCOL_MAX_OBJECT_REQUEST_COUNT");
```

[cryptonote_protocol] some stricter checks on object requests

---

src/cryptonote_core/cryptonote_core.cpp
src/cryptonote_core/cryptonote_core.h

[cryptonote_core] remove 'We are most likely forked' message

---

contrib/epee/src/byte_slice.cpp
tests/unit_tests/epee_utils.cpp

[epee] Fix persisting ptr to std::moved SSO buffer

---

src/rpc/core_rpc_server.cpp
src/rpc/core_rpc_server_error_codes.h

Ref Monero #6577
We'll figure out through usage if the restriction limits need adjustment for sumo (most likey they wont)

[rpc] add a sanity limit to a few RPC in restricted mode

---

src/rpc/rpc_payment.cpp
src/rpc/rpc_payment.h

[rpc] lock access to the rpc payment object

---

contrib/epee/src/mlog.cpp

didnt see any segfaults but anyhow

[epee] avoid null pointer dereferencing

---

src/wallet/wallet2.cpp

[wallet2] fix pick_preferred_rct_inputs

---

src/rpc/core_rpc_server.cpp

[rpc] fix relay_tx error return

---

.github/workflows/build.yml

so we can check on each pr backwards compatibility 
(xenial release fails till #957 is merged)

[workflows] add ubuntu xenial and ubuntu xenial and bionic static builds

---

README.md

Add a workflows badge
Goes along with #974

[readme] add workflows badge

---

README.md

the gaining in size is **huge** ,almost one fifth, we should make it clear

[readme] be precise about pruning

---

.github/workflows/build.yml

Ref for windows build monero #6634

[workflows] rename and update windows build

---

src/cryptonote_protocol/cryptonote_protocol_handler.inl
tests/unit_tests/node_server.cpp

[protocol] show available disk space on synced and advise pruning if low

---

src/cryptonote_core/blockchain.cpp

[blockchain.cpp] fix total_height in getblocks.bin response

---

src/rpc/rpc_payment.cpp

[rpc] fix loading rpc payment data from file

---

src/cryptonote_core/tx_pool.cpp

[dandelion++] fix dandelion++ block template check

---

src/rpc/rpc_payment.cpp

[rpc] fix comparison of seconds vs microseconds

---

src/daemon/rpc_command_executor.cpp

monero #6642 adjusted for sumo

[daemon] remove time based "update needed" status string

---

contrib/depends/packages/native_ccache.mk

[depends] update ccache download link

---

src/cryptonote_core/blockchain.cpp
src/cryptonote_core/blockchain.h

Monero Ref [6651]
Fixes actual diff drift when popping alt chain blocks

[blockchain] fix timestamp/difficulty cache getting out of sync

---

src/cryptonote_core/cryptonote_core.cpp
src/cryptonote_core/tx_pool.cpp
src/cryptonote_core/tx_pool.h

Monero Ref [6671] 
(this is brought in for consistency)

[tx_pool] mine stem txes in fake chain mode

---

CMakeLists.txt
contrib/epee/src/http_auth.cpp
src/device/device_ledger.cpp
src/device_trezor/device_trezor_base.hpp

few minimal changes in order to build, backwards compatibility to 11 is fully retained

[core] switch to c++17

---

src/cryptonote_core/blockchain.cpp
src/cryptonote_core/blockchain.h

jagerman from loki caught this and he is right, it explicitly says that we need one thread no reason to call a pool

[blockchain] thread pool to single

---

contrib/epee/include/ado_db_helper.h
contrib/epee/include/math_helper.h
contrib/epee/include/misc_language.h
contrib/epee/include/net/abstract_tcp_server2.h
contrib/epee/include/net/abstract_tcp_server2.inl
contrib/epee/include/net/abstract_tcp_server_cp.h
contrib/epee/include/net/abstract_tcp_server_cp.inl
contrib/epee/include/net/http_client.h
contrib/epee/include/net/levin_protocol_handler_async.h
contrib/epee/include/net/network_throttle.hpp
contrib/epee/include/soci_helper.h
src/crypto/crypto.cpp
src/gen_multisig/gen_multisig.cpp
tests/net_load_tests/srv.cpp

lets start doing things with c++17

[core] convert all boost::shared_ptr to std::shared_ptr

---

src/daemon/rpc_command_executor.cpp

[daemon] add the total number of INC, OUT and sum of both on print_cn

---

src/daemon/command_parser_executor.cpp
src/daemon/command_parser_executor.h
src/daemon/command_server.cpp
src/daemon/rpc_command_executor.cpp
src/daemon/rpc_command_executor.h

print only the nodes, we are connected to, having an open rpc port

[daemon] add a print_open_cn command

---

contrib/epee/include/net/abstract_tcp_server2.inl

Fixes the occasional error shown on daemon logs `"Setting timer on a shut down object"`
if the object is shut down dont set it then...

[epee]  setting timer on shutdown object error

---

src/device/device_ledger.cpp

[ledger] Fix incorrect lenght of command INS_PREFIX_HASH

---

external/CMakeLists.txt
external/qrcodegen/CMakeLists.txt
external/qrcodegen/QrCode.cpp
external/qrcodegen/QrCode.hpp
src/simplewallet/CMakeLists.txt
src/simplewallet/simplewallet.cpp
src/simplewallet/simplewallet.h

I really enjoyed porting this from Monero (# 6488), fits nicely with the android and the web wallet qr code

[simplewallet] add show_qr_code command

---

README.md

needed by unbound so we dont have to build the in-tree

[readme] add libevent dependency

---

contrib/epee/include/net/abstract_tcp_server2.inl

Fixes inability to shutdown daemon when connected via torsocks. (we had to pkill -9 the daemon when on torsocks till now ....)
(takes a couple of minutes (maybe less) on my server to wrap things up properly and exit)

[p2p] gracefully shutdown daemon when on torsocks

---

src/cryptonote_core/blockchain.cpp

[blockchain] fix theoretical race getting bulk timestamps

---

CMakeLists.txt

[cmake] insert CMAKE_CURRENT_SOURCE_DIR in CMAKE_MODULE_PATH

---

src/simplewallet/simplewallet.cpp

monero # 6537 adjusted for sumo (the boost placeholders)

[simplewallet] add missing calls to on_command

---

src/blockchain_db/testdb.h

[testdb] add override in a couple places where it's missing

---

.github/workflows/build.yml

We are covering everything now i guess

[workflows] add windows and bionic debug builds

---

src/cryptonote_config.h
src/p2p/net_node.inl

[p2p] bring seed node ips to config.h

---

contrib/epee/include/net/http_server_handlers_map2.h
external/easylogging++/easylogging++.cc
src/cryptonote_core/blockchain.cpp
src/rpc/core_rpc_server.cpp

Ref: monero # 6728 and they rush for a release like they always do...

[rpc] error handling fixes

---

src/cryptonote_config.h
src/p2p/net_node.inl

on 167.172.44.84 mainnet seed
**Testnet explorer on http://167.172.44.84**
Steps on #1049 it might need rebasing

[testnet] add another stable testnet seed node and run a testnet explorer on it

---

src/wallet/wallet2.cpp

[wallet2] fix wrong name when checking RPC cost

---

src/blockchain_utilities/blockchain_stats.cpp

[blockchain-stats] fix underreporting size of prunable txs

---

contrib/epee/include/storages/levin_abstract_invoke2.h

[epee] further defending against exceptions in command handlers

---

src/wallet/wallet2.cpp

[wallet2] Fix broken multisig pubkey sorting

---

ZMQ.md
src/common/notify.cpp
src/cryptonote_basic/events.h
src/cryptonote_basic/fwd.h
src/cryptonote_core/blockchain.cpp
src/cryptonote_core/blockchain.h
src/cryptonote_core/cryptonote_core.cpp
src/cryptonote_core/cryptonote_core.h
src/daemon/command_line_args.h
src/daemon/daemon.cpp
src/daemon/daemon.h
src/daemon/main.cpp
src/net/zmq.cpp
src/net/zmq.h
src/rpc/CMakeLists.txt
src/rpc/fwd.h
src/rpc/zmq_pub.cpp
src/rpc/zmq_pub.h
src/rpc/zmq_server.cpp
src/rpc/zmq_server.h
src/serialization/json_object.h
tests/unit_tests/CMakeLists.txt
tests/unit_tests/json_serialization.cpp
tests/unit_tests/json_serialization.h
tests/unit_tests/zmq_rpc.cpp

ref monero # 6418
Major zmq improvements and changes affecting core chain events like new block notify and add tx in pool 
be on the lookout for any bugs
(with some fixes in unit tests to be compatible with sumo)

[zmq] adding ZMQ/Pub support for txpool_add and chain_main events

---

src/rpc/daemon_handler.cpp
src/rpc/daemon_handler.h
src/rpc/daemon_rpc_version.h
src/rpc/message.cpp
src/rpc/message.h
src/rpc/rpc_handler.h
src/rpc/zmq_server.cpp
src/serialization/CMakeLists.txt
src/serialization/json_object.cpp
src/serialization/json_object.h
tests/unit_tests/json_serialization.cpp
tests/unit_tests/zmq_rpc.cpp

Monero Ref # 6601 # 6770 # 6603

[zmq] fixes and optimisations 

---

utils/python-rpc/framework/daemon.py

[python-rpc] fix bad in_peers parameter

---

src/daemon/rpc_command_executor.cpp

[daemon] don't print "(pruned)" for coinbase txes

---

src/wallet/wallet2.cpp

[wallet2] throw a error on wallet initialization failure

---

src/simplewallet/simplewallet.cpp

My Dutch friend @SUMO-Mandarijnen and my Occitan friend @ming79 say that this should give a UTC timestamp (instead of system's local time) and they are absolutely right

[simplewallet] convert seed generation timestamp to UTC

---

src/common/util.cpp
src/daemon/rpc_command_executor.cpp

[daemon] print sampling time in print_net_stats

---

src/cryptonote_core/blockchain.cpp
src/device/device_ledger.cpp

Ref Monero # 6661
(seems big its not, its just two lines, Atom truncated/fixed some whitespaces/tabs on ledger.cpp)

[core] avoid a couple needless copies

---

README.md
external/easylogging++/ea_config.h

[NetBSD] fix NetBSD building and add instructions on readme

---

src/wallet/wallet_rpc_server.cpp

[wallet_rpc_server] use unlock_time in suggested confirmations calc

---

contrib/epee/include/net/abstract_http_client.h
contrib/epee/include/net/http_client.h
contrib/epee/src/abstract_http_client.cpp
src/net/CMakeLists.txt
src/net/http.cpp
src/net/http.h
src/net/parse.cpp
src/net/parse.h
src/wallet/api/wallet.cpp
src/wallet/api/wallet.h
src/wallet/api/wallet2_api.h
src/wallet/api/wallet_manager.cpp
src/wallet/api/wallet_manager.h
src/wallet/wallet2.cpp
src/wallet/wallet2.h
tests/unit_tests/multisig.cpp

[wallet2_api] implement runtime proxy configuration

---

src/blockchain_db/blockchain_db.cpp
src/blockchain_db/blockchain_db.h
src/blockchain_db/lmdb/db_lmdb.cpp
src/blockchain_db/lmdb/db_lmdb.h
src/blockchain_db/testdb.h
src/cryptonote_basic/blobdatatype.h
src/cryptonote_basic/cryptonote_format_utils.cpp
src/cryptonote_basic/cryptonote_format_utils.h
src/cryptonote_core/blockchain.cpp
src/cryptonote_core/blockchain.h
src/cryptonote_core/tx_pool.cpp

[core] avoid some temporary strings when reading off the database

---

src/common/dns_utils.cpp
src/common/threadpool.cpp
src/common/threadpool.h
src/cryptonote_core/blockchain.cpp
src/cryptonote_core/cryptonote_core.cpp
src/ringct/rctSigs.cpp
src/wallet/wallet2.cpp
tests/unit_tests/threadpool.cpp

[threadpooling] restructuring

---

src/ringct/rctSigs.cpp
src/ringct/rctTypes.h

[ringct] fix CLSAG serialization after boost/epee changes

---

src/p2p/net_node.inl

we always build the intree which has api level 21

[p2p] trivial fix on miniupnpc impl

---

src/cryptonote_config.h
src/p2p/net_node.inl

cleaner access on cryptonote_config.h than previous arrangement

[p2p] cleaner arrangement of seed nodes

---

src/cryptonote_config.h
src/daemon/rpc_command_executor.cpp
src/p2p/net_node.inl

on mainnet (works on testnet and stagenet as well since we are using the same IPs)
(steps on #1133)

[daemon] mark seed nodes on print connections

---

src/device/device_ledger.cpp
src/device/device_ledger.hpp

[ledger] fix protocol with Ledger's HW when using CLSAG

---

src/checkpoints/checkpoints.cpp
src/debug_utilities/dns_checks.cpp

[checkpoints] add a new domain with updated DNS checkpoints (DNSSEC protected)

---

src/cryptonote_config.h
src/cryptonote_core/blockchain.cpp
src/cryptonote_core/blockchain.h
src/rpc/core_rpc_server.cpp
src/rpc/core_rpc_server_commands_defs.h
src/rpc/daemon_handler.cpp
src/rpc/message_data_structs.h
src/serialization/json_object.cpp
src/simplewallet/simplewallet.cpp
src/wallet/node_rpc_proxy.cpp
src/wallet/node_rpc_proxy.h
src/wallet/wallet2.cpp
src/wallet/wallet2.h

Ref Monero # 6754 adjusted for sumo
I dont know if i want this in. It seems disproportionate to the thing it improves and is already working without major issues.
Let's decide before preparing for our HF.

[tx unlock time] use recent block times for unlock time

---

src/daemon/command_parser_executor.cpp
src/daemon/command_parser_executor.h
src/daemon/command_server.cpp
src/daemon/rpc_command_executor.cpp
src/daemon/rpc_command_executor.h

Fetches and prints the dns checkpoints from the updated url

[daemon] add a 'print_checkpoints' command

---

src/daemon/main.cpp

[daemon] warn if data dir resides on FAT32 volume (Windows)

---

src/cryptonote_core/cryptonote_core.cpp
src/cryptonote_core/cryptonote_core.h

by comparing it to a dns txt record (dnssec)
repeated every 15 mins

[version] display warning if our version is other than the latest

---

contrib/depends/packages/qt.mk

Previous one wasn't working as well any more. 
This seems more solid, if this fails again in the near future i ll upgrade qt in a newer version

[depends] update qt download link (again)

---

src/simplewallet/simplewallet.cpp
src/simplewallet/simplewallet.h
src/wallet/wallet2.cpp
src/wallet/wallet2.h
src/wallet/wallet_errors.h

[wallet2] skip reorgs exceeding max-reorg-depth wallet setting

---

src/rpc/core_rpc_server.cpp

[core rpc server] on_get_blocks - forward bootstrap daemon error

---

src/blockchain_utilities/blockchain_export.cpp
src/blockchain_utilities/blockchain_import.cpp
src/blockchain_utilities/bootstrap_file.cpp
src/blockchain_utilities/bootstrap_file.h

[blockchain_utilities] allow setting start block on export

---

.github/workflows/build.yml

instead of grabbing it already built from sumogr's repo - get boost from official as well

workflows: build openssl on instance

---

contrib/epee/include/net/levin_protocol_handler_async.h

it will be handled in a different way

Revert "[epee] async_protocol_handler_config-fix deadlock"

---

README.md
contrib/epee/include/byte_slice.h
contrib/epee/include/net/abstract_tcp_server2.h
contrib/epee/include/net/abstract_tcp_server2.inl
contrib/epee/include/net/net_ssl.h
contrib/epee/src/byte_slice.cpp
contrib/epee/src/net_ssl.cpp
src/rpc/core_rpc_server.cpp
src/simplewallet/simplewallet.cpp
src/wallet/wallet_rpc_server.cpp
src/wallet/wallet_rpc_server.h
src/wallet/wallet_rpc_server_commands_defs.h
sumokoin_utilities/python-rpc/console.py
tests/unit_tests/epee_utils.cpp

[epee] allow byte_stream->byte_slice conversion to shrink unused buffer space
[epee] don't log raw packet data
[ssl] store RPC SSL key/cert for consistent authentication between runs
[python-rpc] adapt urlparse for python3
[readme] update libzmq minimum version to 4.2.0 for zmq_send_const
[wallet-rpc] add scan_tx command
[wallet-rpc] return output keys with incoming transfers
[simplewallet] xmr to sumo leftovers

Request to merge dev to master

---

src/cryptonote_core/blockchain.cpp
src/cryptonote_core/blockchain.h
src/cryptonote_core/cryptonote_core.cpp
src/cryptonote_core/cryptonote_core.h
src/cryptonote_protocol/cryptonote_protocol_handler.inl
tests/unit_tests/node_server.cpp

can bring syncing in a standstill

[p2p] revert strict p2p sanity check causing false positives

---

src/cryptonote_core/blockchain.cpp
src/cryptonote_core/blockchain.h
src/cryptonote_core/cryptonote_core.cpp
src/cryptonote_core/cryptonote_core.h
src/cryptonote_protocol/cryptonote_protocol_handler.inl
tests/unit_tests/node_server.cpp

can bring syncing in a standstill

[p2p] revert strict sanity checks delaying sync by causing false positives

---

src/rpc/core_rpc_server.cpp
sumokoin_utilities/python-rpc/framework/wallet.py

[python-rpc] add function for new scan_tx RPC
[rpc] fix sumokoind --rpc-ssl disabled and --non-interactive combination

[rpc] couple of fixes in python rpc and rpc 
