src/wallet/wallet2.cpp, src/wallet/wallet_rpc_server.cpp, src/wallet/wallet_rpc_server.h, src/wallet/wallet_rpc_server_commands_defs.h
This obsoletes the need for a lengthy blockchain rescan when
a transaction doesn't end up in the chain after being accepted
by the daemon, or any other reason why the wallet's idea of
spent and unspent outputs gets out of sync from the blockchain's.
Credit @ moneromooo-monero
=> Add rescan_spent RPC command

src/cryptonote_config.h, src/cryptonote_core/blockchain.cpp, src/cryptonote_core/difficulty.cpp, src/cryptonote_core/difficulty.h
- Problem: Current diff calculation inheriting from Cryptonote
codebase has serious flaw that cannot adjusted fast enough to multi-pool hashrate
flash (from Nicehash, for example). This was pointed out by MRL-0006 here:
https://www.overleaf.com/articles/difficulty-adjustment-algorithms-in-cryptocurrency-protocols/ytcxbjvzrpbp/viewer.pdf
- Some suggestions to solve the issue can be found here:
https://github.com/monero-project/research-lab/issues/3
and here:
https://github.com/zcash/zcash/issues/147
especially valuable one from @zawy12 (Zcash)
- Sumokoin follows Zcash approach to make difficulty more responsive to hashrate surge
leaving attackers much less profitable.
Please note that this will require a hardford however. Comments are welcome.
=> Adjust difficulty calculation algorithm

src/wallet/wallet_rpc_server.cpp, src/wallet/wallet_rpc_server.h
This is already implemented in cli wallet, now ported to RPC to avoid similar error when transfer big amount
=> Fix 'transaction too big' error for RPC transfer_split method

src/daemonizer/posix_fork.cpp
request to change the name of the standard output log file from bitmonero.daemon.stdout.stderr to sumokoin.daemon.stdout.stderr. If sumokoind and monerod is started on the same machine a conflict occurs as both daemons try and write to the same file.
ERROR: sumokoin/src/daemonizer/posix_fork.cpp:22 Unable to open output file: /tmp/bitmonero.daemon.stdout.stderr
=> Change log file name in posix_fork.cpp

src/cryptonote_config.h
To address syncing stall when network connection is slow
=> Reduce default block sync size to 10

CMakeLists.txt
Fixed compilation on OS X Sierra.
=> OSX fix: Change logic of testing for libunwind on OSX and ARM

CMakeLists.txt, contrib/epee/include/console_handler.h, contrib/epee/include/net/net_helper.h, src/simplewallet/simplewallet.cpp, src/wallet/api/wallet.cpp
Ok this fixes 5 problems:
- The CMakeLists.txt file contained a typo
- The updated transactions call was using an outdated interface.
- The simplewallet did not build due to incorrect refresh calls.
- Missing return statement in net_helper
- Unused variable was removed
=> Fix several issues with last PRs

src/common/CMakeLists.txt
Identical patch of
https://github.com/monero-project/monero/pull/1674
Failed to compile on ubuntu 16.04 with gcc6.30, build works after applying said patch.
=> Fix compile bug patched in Monero

src/cryptonote_protocol/cryptonote_protocol_handler.inl
[sumokoind] Added blocks remaining count during syncronisation and syncing percentage  ( <99%)
@Jorropo commit on Monero
https://github.com/monero-project/monero/commit/c24a0af9f1a3c809ba6c11a703984fedabaa6e9f#diff-2378334cb79d20b2cacbd5a25fe60ba9R1224
=> [sumokoind] Added blocks remaining count during syncronisation and syncing percentage [Jorropo commit on Monero]

src/wallet/wallet_rpc_server.cpp
so that wallet rpc won't be blocked from exiting via rpc command
=> [Wallet RPC] let stop_wallet rpc work even no wallet open

src/wallet/wallet2.cpp
Vu following our discussion, XMR has caught the bug which was reported with the 0 pool tx confirmations on cli (which i port here), please fix the similar bug on the rpc ( showin on get_transfer_by_txid, etc... for txs still on pool)  by explicitly declaring them to zero as per your suggestion so we can pull on Monero too
=> set confirmations to 0 for pool txes on wallet

CMakeLists.txt, contrib/epee/src/mlog.cpp, contrib/epee/src/net_ssl.cpp, src/lmdb/error.cpp, src/rpc/core_rpc_server.cpp, src/wallet/wallet2.cpp, src/wallet/wallet_rpc_server.cpp
- wallet: fix certificate fingerprint length check
- wallet_rpc_server: use original addresses in destinations in get_transfers
- net_ssl: free certs after setting them up
- rpc: fail update RPC when running offline
- cmake: fix incorrect hint for OPENSSL_ROOT_DIR
- mlog: default to not showing SSL errors
- error: fix compile error on windows with depends
Up to upstream commit# https://github.com/monero-project/monero/commit/1607419e3817d12a8fed307d1e0f8fead5bbda69
=> [MISC] Various fixes for SSL and wallet/rpc

CMakeLists.txt, contrib/depends/packages/openssl.mk, contrib/epee/include/net/net_helper.h, contrib/epee/include/net/net_utils_base.h, src/cryptonote_basic/miner.cpp, src/cryptonote_basic/miner.h, src/device/device_ledger.cpp, src/device/device_ledger.hpp, src/p2p/net_peerlist_boost_serialization.h, src/rpc/core_rpc_server.cpp, src/rpc/daemon_handler.cpp
- epee: fix SSL autodetect on reconnection
- miner: fix double free of thread attributes
- miniupnpc: update to build on BSD
- p2p: fix GCC 9.1 crash
- Fix GCC 9.1 build warnings
- cmake: do not use -mmitigate-rop on GCC >= 9.1
Up to upstream commit# https://github.com/monero-project/monero/commit/fd0cf689ddb62c07fa9d86ca6e070860c51669cc
=> [ALL] Various fixes and updates on SSL, miner, p2p, upnp and GCC build

src/wallet/wallet2.cpp
To fix error "Known ring does not include the spent output: nnn"
that may fire at newly-restored wallet on creating tx
=> [WALLET] Force to include real output when having known ring

src/wallet/api/wallet.cpp
- getTxKey method throws an exception, e.g., when user declines txKey export
Ref: https://github.com/monero-project/monero/pull/5673/commits/097cca59c1a9a9a5893174419ee888c66465a1cf
=> [Wallet api] Catch getTxKey exception

src/p2p/net_peerlist.h
Older nodes don't pass that information around
Ref: https://github.com/monero-project/monero/pull/5669
=> [P2P] Don't forget pruning seed or public RPC port when updating peers

contrib/epee/include/net/levin_protocol_handler_async.h, src/p2p/net_node.inl
- p2p: propagate out peers limit to payload handler
- p2p: close the right number of connections on setting max in/out peers
Upstream: https://github.com/monero-project/monero/pull/5674/commits/fcbf7b3f747b068f993d22ec8deabea643254da3
and https://github.com/monero-project/monero/pull/5674/commits/098aadf084ad0ab0584e92e8f2bc5667b7cd5c89
=> [P2P] A couple minor fixes

src/simplewallet/simplewallet.cpp
- The wallet was ignoring --restore-height and --restore-date params and
prompting for them again.
- Don't ask about mining when running a command line
Ref: https://github.com/monero-project/monero/pull/5656/commits/8ccc30b163c45de9a9a6ec44a38cabf22dcf924b
and https://github.com/monero-project/monero/pull/5685/commits/a604241ef66cdb3f5c8b8af27df5404f8eda8eb0
=> [Wallet] Fix --restore-date usage

src/wallet/wallet2.cpp
Ref: https://github.com/monero-project/monero/pull/5672/commits/b2bfcab6182706cd55033ee539f88ce4dd07523b
=> [Wallet] Fix change subaddress mixup when sending pre rct outputs

src/cryptonote_core/blockchain.cpp
This happens often when a pre-pruning node asks a pruned node
for data it does not have
Ref: https://github.com/monero-project/monero/pull/5651/commits/c382677ee3a4db6b4f665b0d7118e1993989773b
=> [Blockchain] Silence an error getting blocks for pruned nodes

contrib/depends/Makefile, contrib/depends/funcs.mk, contrib/depends/packages/eudev.mk, contrib/depends/packages/expat.mk, contrib/depends/packages/hidapi.mk, contrib/depends/packages/icu4c.mk, contrib/depends/packages/ldns.mk, contrib/depends/packages/libiconv.mk, contrib/depends/packages/ncurses.mk, contrib/depends/packages/packages.mk, contrib/depends/packages/protobuf.mk, contrib/depends/packages/readline.mk, contrib/depends/packages/sodium-darwin.mk, contrib/depends/packages/sodium.mk, contrib/depends/packages/unwind.mk, contrib/depends/packages/zeromq.mk, contrib/depends/toolchain.cmake.in
- Readline support is now compiled with the ncurses backend.
- To speedup the depends cached builds, remove some some clutter from the package
files. This mainly incldues removing all the shared libraries and .la
linker files. It also gives stronger guarantees that monero only links
the static libs without any external rvalues.
- Packages can now be built individually and for each stage. This allows
easier debugging.
Ref: https://github.com/monero-project/monero/pull/5690/commits
=> [BUILD] Fix readline compilation

src/blockchain_db/lmdb/db_lmdb.cpp
to avoid errors when the txn is too large
Ref: https://github.com/monero-project/monero/pull/5666/commits/ba035bf827537ada447a51f0954679e247c10ff2
=> [LMDB] Commit pruning txn at checkpoints

src/crypto/cn_heavy_hash.hpp
=> [CRYPTO] Make heavy hash work at cross-compiling for MINGW (2)

contrib/depends/packages/ncurses.mk, contrib/depends/packages/readline.mk, src/crypto/keccak.c, src/p2p/net_node.inl, src/rpc/core_rpc_server.cpp, src/wallet/wallet_rpc_server.cpp, tests/functional_tests/transfer.py, tests/unit_tests/keccak.cpp
- wallet_rpc_server: fix get_bulk_payments with short payment ids
- p2p: don't connect to more than one IP per class B if we can\
- keccak: guard against misaligned memory accesses on ARM
- depends: further fixes for readline and ncurses
Up to upstream commit https://github.com/monero-project/monero/commit/fd3ff741644152ed559fcf79550435d3df75b764
=> [MISC] Fixes for get_bulk_payment, p2p, keccak, and depends

contrib/epee/include/net/abstract_tcp_server2.h, contrib/epee/include/net/net_utils_base.h, contrib/epee/src/net_utils_base.cpp, src/daemon/command_parser_executor.cpp, src/daemon/command_parser_executor.h, src/daemon/command_server.cpp, src/daemon/rpc_command_executor.cpp, src/daemon/rpc_command_executor.h, src/net/error.h, src/net/parse.cpp, src/net/parse.h, src/p2p/net_node.h, src/p2p/net_node.inl, src/p2p/net_node_common.h, src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server.h, src/rpc/core_rpc_server_commands_defs.h, tests/unit_tests/ban.cpp, tests/unit_tests/net.cpp
Also, store network address directly in blocked host list
rather than their string representation
Ref: https://github.com/monero-project/monero/pull/5363/commits
=> [NETWORK] Allow blocking whole subnets

contrib/epee/include/net/abstract_tcp_server2.inl
The lock is meant for the network throttle object only,
and this should help coverity get unconfused
Ref: https://github.com/monero-project/monero/pull/5531/commits/9a6006bad89db877ee082c7dfa01da76efd6231a
=> [abstract_tcp_server2] Move some things out of a lock

contrib/epee/include/net/abstract_tcp_server2.h, contrib/epee/include/net/abstract_tcp_server2.inl, contrib/epee/include/net/http_server_impl_base.h, contrib/epee/include/net/local_ip.h, contrib/epee/include/net/net_parse_helpers.h, contrib/epee/include/net/net_utils_base.h, contrib/epee/src/net_helper.cpp, contrib/epee/src/net_utils_base.cpp, src/daemon/rpc_command_executor.cpp, src/net/parse.cpp, src/net/parse.h, src/p2p/net_node.cpp, src/p2p/net_node.h, src/p2p/net_node.inl, src/p2p/net_peerlist_boost_serialization.h, src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server_commands_defs.h, src/rpc/rpc_args.cpp, src/rpc/rpc_args.h, src/wallet/wallet_rpc_server.cpp
New cli options (RPC ones also apply to wallet):
--p2p-bind-ipv6-address (default = "::")
--p2p-bind-port-ipv6    (default same as ipv4 port for given nettype)
--rpc-bind-ipv6-address (default = "::1")
--p2p-use-ipv6          (default false)
--rpc-use-ipv6          (default false)
--p2p-require-ipv4      (default true, if ipv4 bind fails and this is
true, will not continue even if ipv6 bind
successful)
--rpc-require-ipv4      (default true, description as above)
ipv6 addresses are to be specified as "[xx:xx:xx::xx:xx]:port" except
in the cases of the cli args for bind address.  For those the square
braces can be omitted.
Ref: https://github.com/monero-project/monero/commit/155475d9719694c838297cb3fbc94a2782329d46
=> [NETWORKING] Add IPv6 support

contrib/epee/include/net/http_protocol_handler.inl, contrib/epee/include/net/http_server_handlers_map2.h, src/cryptonote_config.h, src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server.h
- Make bans control RPC sessions too
- Auto-ban some bad requests. Drops HTTP connections whenever
response code is 500
Ref: https://github.com/monero-project/monero/pull/5649/commits/a182df21d0760e037219a6ae0a31b26b00489f22
=> [RPC] Bans for (bad) RPC connections

src/wallet/wallet2.cpp
- Ignore null keys stored as tx keys as those are invalid.
TX key cache can be full of zero keys which blocked tx key
recovery using Trezor
Ref: https://github.com/monero-project/monero/pull/5662/commits/64fb0f872aa404e65514bdf913158c34d21bc8a4
=> [DEVICE] Fix tx_key caching

src/cryptonote_core/cryptonote_tx_utils.cpp, src/p2p/net_peerlist.h, src/wallet/wallet2.cpp, tests/unit_tests/ringct.cpp, tests/unit_tests/rolling_median.cpp
According to the docs, std::random_shuffle is deprecated in C++14
and removed in C++17. Since std::shuffle is available since C++11
as a replacement and monero already requires C++11, so it is a
good idea to use std::shuffle instead.
The choice of random number generator was inspired by the other
usages of std::shuffle in the codebase; since the original
std::random_shuffle made no guarantees whatsoever about the quality
of its randomness, this does not introduce problems there.
Ref: https://github.com/monero-project/monero/pull/5727
=> [ALL] Replace std::random_shuffle with std::shuffle

src/blockchain_db/lmdb/db_lmdb.cpp
A lot of new indices have been added recently, and 20 isn't enough
for them plus new DBs opened during format migrations.
Ref: https://github.com/monero-project/monero/pull/5817/commits/50ec40ea16f281690aeded37973dc582ddf38843
=> [LMDB] Increase max_dbs from 20 to 32

src/cryptonote_core/blockchain.cpp
Apply the overflow logic used for computing already_generated_coins in
the main chain to alternative chains.
Ref: https://github.com/monero-project/monero/pull/5819/commits/07cb087e5dd932c7afb9a7b2eafb99a003929e1f
=> [Blockchain] Fix alt chain generated coins overflow

src/crypto/crypto.cpp
Small nonces were not mentioned in the QuarksLab report. The nonce
should be unbiased, so small values must be equally considered.
Ref: https://github.com/monero-project/monero/pull/5807/commits/4b1df4e50ffac182cae53d049b2ef4e0a5083340
=> [Crypto] Fix for biased signature nonce

src/device/device_io_hid.cpp
hid_error() could return a null, which causes the program to crash
with std::logic_error(), since a string cannot take a null in
its constructor.
Ref: https://github.com/monero-project/monero/pull/5800/commits/6ca033d2784cbdf886b54d4acc4b8f6e1417cd22
=> [DEVICE] Fix null return from hid_error()

.travis.yml, README.md, contrib/depends/README.md, contrib/depends/packages/ldns.mk, contrib/depends/packages/openssl.mk, contrib/depends/packages/packages.mk, contrib/depends/toolchain.cmake.in
It is now possible to cross compile to riscv64 with `make depends
target=riscv64-linux-gnu` in the top level Makefile.
Ref: https://github.com/monero-project/monero/pull/5702/commits/13c0b8c265727ae1e0e9c604ea3fbf44bb749f2c
=> [Cross-compiling] Add depends riscv 64 bit support

src/crypto/CryptonightR_JIT.c
The value was positive rather than zero, but the caller only
checks for negative errors
Ref: https://github.com/monero-project/monero/pull/5731/commits/c393e824d6a571f969088d9bd99c5a899fbee353
=> [Crypto] CryptonightR_JIT: fix return value on error

src/simplewallet/simplewallet.cpp, src/simplewallet/simplewallet.h
Usage scenario: User forgets to write down their restore height
and would like to obtain it to make restoring the wallet at a
later point in time faster.
https://github.com/monero-project/monero/pull/5743/commits/65f29a83c899b44b2f134e0aa34ddfe104244ae4
=> [Simplewallet] Add restore_height command

src/cryptonote_core/cryptonote_tx_utils.h, src/simplewallet/simplewallet.cpp, src/wallet/api/transaction_history.cpp, src/wallet/wallet_rpc_server.cpp
instead showing original address (without payment id) that makes
user be confused
Ref: https://github.com/monero-project/monero/pull/5750/commits/884df82db37d2f93151efc9b3dd165062444c7e6
=> [Wallet] Show integrated address for outgoing transfers

src/wallet/message_store.cpp, src/wallet/message_transporter.cpp, src/wallet/message_transporter.h
Using the Bitmessage mechanism of chans instead of normal
addresses as the basis for the auto-config mechanism of
the MMS has advantages:
They are faster because no initial key exchange is needed -
everybody who knows the chan name knows already the key
(or better said, can derive the key from the chan name).
Especially in connection with the PyBitmessage app that the MMS
uses chans have another advantage over normal addresses: It's
possible to delete them manually if anything goes wrong and the MMS
has no chance to delete them automatically.
Just for completeness' sake it should be noted that one should not
bring this change into service exactly in the middle of an
already-running auto-config process.
Ref: https://github.com/monero-project/monero/pull/5778/commits/8703aa59db18918d6d6687c2 …
=> [MMS] Use chans instead of normal addresses for auto-config

contrib/epee/include/net/levin_protocol_handler_async.h
Without this change a connection that is explicitly close()d is not
properly deleted and so hangs around erroneously in the list of
connections (as a `before_handshake`) even though it is actually closed.
From:
https://github.com/loki-project/loki/commit/9a4c1262d49505812d1b8d2d0307c4f5d5a9474b
=> On close() a connection delete it as well

src/p2p/net_node.inl
When an incoming peer connects, the daemon establishes an outbound peer
connection to ping the remote to see if its advertised p2p port works
before adding to the whitelist.
These aren't really outbound peers, though, and will never get beyond
the handshake stage, so don't count them as outs (unless they hang
around for at least 10 seconds), so that we don't kill *good* outbound
peers when we think we have too many outgoing p2p connections.
From:
https://github.com/loki-project/loki/commit/73577194863d55f48c2f4b6b7150ab17bc711812
=> Don't count pingback connections as out conns

src/crypto/crypto.cpp, src/crypto/crypto.h, src/crypto/random.c, src/crypto/random.h, src/wallet/wallet2.cpp
That lets the user add custom entropy to the PRNG by hashing
the new data and xoring the resulting hash with the PRNG state.
Ref: https://github.com/monero-project/monero/pull/5609/commits/1dc3b1a516332f12a4bd8fd8dd80695a003d1d98
=> [Wallet] Add --extra-entropy command line flag

src/ringct/bulletproofs.cc, src/ringct/rctOps.cpp, src/ringct/rctOps.h, src/ringct/rctSigs.cpp, tests/performance_tests/main.cpp, tests/performance_tests/rct_mlsag.h, tests/unit_tests/ringct.cpp
- Removes redundant point conversions in MLSAG verification
- Replaces public key hash-to-point zero checks with round hash-to-scalar zero checks
- Updates tests
- Improves error messages
Ref: https://github.com/monero-project/monero/pull/5707
=> [RingCT] MLSAG speedup and zero-hash check

src/rpc/CMakeLists.txt, src/rpc/bootstrap_daemon.cpp, src/rpc/bootstrap_daemon.h, src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server.h
Implemented `--bootstrap-daemon-address auto` mode.
Allows to sync and use the wallet while the daemon is syncing with
the network.
* **While the daemon is syncing**
it will automatically select random public node (node that is
running with `--public-node` mode enabled) to serve incoming
requests (i.e. will use it as a remote node). If currently
selected public node fails, the daemon will switch to another
randomly chosen public node.
* **Once the daemon is fully synced**
it will use the local blockchain to serve incoming requests,
i.e. operating in normal mode.
Ref: https://github.com/monero-project/monero/pull/5799/commits/082730b6e569e155988df5c5b376c45fba56b396
=> [DAEMON] Automatic bootstrap daemon switching

src/cryptonote_protocol/cryptonote_protocol_handler.inl
Ref: https://github.com/monero-project/monero/pull/5806/commits/69465e3d83c49000745929694946c92d91981f9f
=> [CORE] Fix '--no-sync', ignore new blocks and txes

src/simplewallet/simplewallet.cpp
Trivial display fix on incoming outputs info. "spent" was always there on on_money_spent but there was no "received" on on_money_received
=> [WALLET] Add "received" on incoming outputs info

contrib/epee/include/syncobj.h
under (misspelled) WINDWOS_PLATFORM guard
Ref: https://github.com/monero-project/monero/pull/5814/commits/bdcdb0e81326e9871d0913309033336f8096d8d8
=> [EPEE] Remove unused code

src/cryptonote_core/cryptonote_core.cpp
Tone it down a bit so it starts hitting from 15 minutes instead of 10 minutes (intervals were 10, 20, 30, 60, 90 minutes - i changed it to 15, 30, 45, 60, 90 minutes).
I did so cause we have twice the difficulty retargeting of Monero (4 minutes instead of 2) so in the function that calculates the probability 
```
const time_t time_boundary = now - static_cast<time_t>(seconds[n]);
for (time_t ts: timestamps) b += ts >= time_boundary;
const double p = probability(b, seconds[n] / DIFFICULTY_TARGET);
```
the numerator (where time in seconds is ) should be multiplied by 2 since the denominator is twice as big in sumo. I use 15 minutes as starting point instead of 20 just to be safe, you can double the initial argument
`static const unsigned int seconds[] = { 5400, 3600, 1800, 1200, 600 };` …
=> [CORE] Tone down the warning of excessive blocks

src/blockchain_utilities/blockchain_blackball.cpp, src/wallet/api/wallet.cpp, src/wallet/wallet2.cpp
Change shared-ringdb folder name to sumo-shared-ringdb cause if someone uses the same machine to run monero or any other monero fork that hasnt changed the name the shared-ringdb folder gets overwritten (it is created in /root)
=> [CORE] Important!!! change shared-ringdb folder to sumo

src/p2p/net_node.inl, src/p2p/p2p_protocol_defs.h
With this, nodes include version on their node data structure which is grabbed by the local node and info is displayed on the daemon if the remote node is on a different version than ours **(Peer {IP} has a different version than ours: {version})** or if no version is received **(Peer {IP} did not provide version information it must be Morioka 0.5.1.1 or earlier)** . 
It gives a good general idea in real time on what versions of sumokoin the network is structured
It will be spammy till the first release that includes this cause nodes at the moment are not transmitting version.
Partly based on https://github.com/angrywasp/nerva/commit/e95bb65c2b628dae04baab86b2397f0d1f72b860
( they used something similar to block nodes on different versions for reasons of their own)
=> [P2P] Inform when remote is on a different version

src/daemon/rpc_command_executor.cpp
The output of print_cn (print_connections) was a mess after the introduction of more info like SSL and IPv4 or v6 and so on. This makes it more tidy and more readable. Please check on your displays as well to confirm same.
( I dont know if the width for the remote address (30) can accommodate properly IPv6 addresses length, i left it at 30 as I found it, if its not enough for IPv6 we'll change it)
=> [DAEMON] Better print connections output

src/p2p/net_node.h, src/p2p/net_node.inl
Also remove the delta time fixup, since we now ignore those
as they're attacker controlled
Ref: https://github.com/monero-project/monero/pull/5839/commits/e353e3d7571f14c147d160f9e0e1bc3ab8833ffc
=> [P2P] Sanitize peer lists

src/daemon/command_parser_executor.cpp, src/daemon/command_parser_executor.h, src/daemon/command_server.cpp, src/daemon/rpc_command_executor.cpp, src/daemon/rpc_command_executor.h
To set URL of a 'bootstrap' remote daemon that the connected
wallets can use while this daemon is still not fully synced
Ref: https://github.com/monero-project/monero/pull/5840/commits/063eebbd434d25fc7880edfd31d33d602b9ff306
=> [Daemon] Implement 'set_bootstrap_daemon' command

src/simplewallet/simplewallet.cpp, src/wallet/wallet2.cpp, src/wallet/wallet2.h, src/wallet/wallet_rpc_server.cpp, src/wallet/wallet_rpc_server_commands_defs.h, tests/functional_tests/transactions_flow_test.cpp, utils/python-rpc/framework/wallet.py
One considers the blockchain, while the other considers the
blockchain and some recent actions, such as a recently created
transaction which spend some outputs, but isn't yet mined.
Typically, the "balance" command wants the latter, to reflect
the recent action, but things like proving ownership wants
the former.
This fixes a crash in get_reserve_proof, where a preliminary
check and the main code used two concepts of "balance".
Ref: https://github.com/monero-project/monero/pull/5855/commits/2ec455df1f82148733c4ac268d22e9c51a690b14
=> [Wallet] Fix mismatch between two concepts of "balance"

external/db_drivers/liblmdb/mdb_dump.c, external/db_drivers/liblmdb/mdb_load.c
mdb_load wasn't properly inserting escaped backslashes into the data.
mdb_dump wasn't escaping backslashes when generating printabl
Ref: https://github.com/monero-project/monero/pull/5857/commits/e907305c6c5ee722519ef67911e386490b9a23af
=> [LMDB] mdb_dump/load fix backslash escaping - ITS#9068

tests/unit_tests/net.cpp, tests/unit_tests/output_distribution.cpp
- output_distribution: fix uninitialized values
- net: fix build with CLANG 8 and boost 1.69
=> [Unit_tests] Some fixes

contrib/depends/packages/packages.mk
The unwind package is being attempted to be built on
Windows and Mac when it should only be built on Linux.
Ref: https://github.com/monero-project/monero/pull/5858/commits/5f4bd92e06f0cee3ab9274440c3807f2047fc190
=> [Cross-Build] Fix Travis build on Windows + Mac

src/p2p/net_node.inl
I downgraded to p2p log level 1 its very nice now cause it comes right after the new incoming or outgoing connection info. Its not spamming at all. I ve tested it with fake versions as well and it seems quite alright
Eg.
2019-09-09 15:24:09.860 I [54.37.131.222:40524 69404eff-95db-469c-bfd0-ad6d5a403c60 INC] NEW CONNECTION
2019-09-09 15:24:09.970 I Peer 54.37.131.222:40524 did not provide version information it must be Morioka 0.5.1.1 or earlier
2019-09-09 15:24:09.970 I switching safe mode on
2019-09-09 15:24:09.970 I clearing used stripe peers
2019-09-09 15:24:09.970 I [54.37.131.222:40524 INC] CONNECTION FROM 54.37.131.222 REFUSED, too many connections from the same address
2019-09-09 15:24:09.971 I [54.37.131.222:40524 INC] [182] state: closed in state normal
2019-09-09 15:24:09.971 I …
=> [P2P] Downgrade node version info to p2p log level 1

CMakeLists.txt
Ref: https://github.com/monero-project/monero/pull/5869/commits/6e46b06308cd2b4427d9810e5146b434b5d225cb
=> [CMake] Ensure PYTHON_EXECUTABLE is set

src/rpc/core_rpc_server.cpp
Best case is an address mined previously and it'll get returned,
worst case it was never initialized in the first place
Ref: https://github.com/monero-project/monero/pull/5872/commits/495a7e5b97b3795ac598e699a659f50ec0d9a313
=> [RPC] Don't include an address in mining_status when not mining

src/cryptonote_protocol/cryptonote_protocol_handler.inl
It's not great and seems vulnerable to peers lying to cause disconnections of other peers, so we'll have to come up with a better way later
=> [Core] Revert disconnection of peers when we're syncing

src/simplewallet/simplewallet.cpp, src/simplewallet/simplewallet.h, src/wallet/wallet2.cpp
Reopening.
This time no ANSI escape codes (that had some issues with windows) used exclusively epee message write tools. Not that fancy, had to abandon some things cause they are not so versatile but at least it works with all os and the outcome is ok. (fixed the already merged lock screen as well where i  had used ansi codes as well)
(By the way the fact that pasted seed words doesnt appear on windows cmd although the restoration of the deterministic wallet works ok on entering is an irrelevant bug it exists in previous releases and i think its on monero too. I guess it is the wipeable_string or something I ll see to it later)
=> [Simplewallet] Improve the look of simplewallet

src/simplewallet/simplewallet.cpp
I was trying to fix the bug you have mentioned @quangvu3 about the seed not being displayed when inputted in windows prompt while it was displayed on Linux and then it hit me. The bug is the other way round. Passwords, private keys and seed are not supposed to be shown when inputted. The problem was with linux. A bool was set to false while it was supposed to be true
`auto pwd_container = tools::password_container::prompt(false, prompt, true);`
This is defined at password.h
`static boost::optional<password_container> prompt(bool verify, const char *mesage = "Password", bool hide_input = true);`
~~I dont know why it was working on windows~~ (its the tty) and not on linux (an epee thing obviously) anyway it now works on both os, wipeable strings inside password containers are not supposed …
=> [Simplewallet] Fix password display bug on linux

src/simplewallet/simplewallet.cpp
Disable the language list with the non-english characters. It was not working more often than it did and depending on the user's os setup it either threw junk chars or the panel froze and you had to run with the english list flag (just disabled it - did not remove the code in case something better comes up later on).
Deprecated the annoying bgmining option on wallet initiation as an info message only
=> [Simplewallet] Fix language list to only show English + deprecate background mining option

src/cryptonote_config.h, src/cryptonote_core/blockchain.cpp, tests/core_tests/chaingen_main.cpp, tests/core_tests/rct.cpp, tests/core_tests/rct.h
To avoid txs being fingerprinted by some custom wallets that ignored this
=> [Blockchain] Enforce 10 block age for spending outputs

CMakeLists.txt
With this change, building the iwyu target will provide information
on unused headers, which can be removed to reduce compilation times.
=> [Build] Add the iwyu target to get information on unused headers

src/simplewallet/simplewallet.cpp
Windows wallet lock is disabled by default you have to enable it manually by typing lock but there is no reason not to be nicer (made fonts bold as well)  :)
=> [Simplewallet] Lock screen vanity fix (windows)

src/cryptonote_core/tx_pool.cpp
The 98th percentile position in the agebytes map was incorrectly
calculated: it assumed the transactions in the mempool all have unique
timestamps at second-granularity. This commit fixes this by correctly
finding the right cumulative number of transactions in the map suffix.
This bug could lead to an out-of-bounds write in the rare case that
all transactions in the mempool were received (and added to the mempool)
at a rate of at least 50 transactions per second. (More specifically,
the number of *unique* receive_time values, which have second-
granularity, must be at most 2% of the number of transactions in the
mempool for this crash to trigger.) If this condition is satisfied, 'it'
points to *before* the agebytes map, 'delta' gets a nonsense value, and
the value of 'i' in the first …
=> [CORE] Fix bug in mempool get_transaction_stats histogram calculation

src/cryptonote_core/blockchain.cpp
Such a template would yield an invalid block, though would require
an attacker to have mined a long blockchain with drifting times
(assuming the miner's clock is roughly correct)
Ref: https://github.com/monero-project/monero/pull/5902/commits/4a7fcfc42503ab7295e8ca869492add548bdbbb8
=> [Blockchain] Keep block template timestamp not above recent median

contrib/epee/include/net/abstract_tcp_server2.inl
Resetting the timer after shutdown was initiated would keep a reference to the object inside ASIO, which would keep the connection alive until the timer timed out
=> [abstract_tcp_server2] Fix lingering connections

src/simplewallet/simplewallet.cpp
Revert to old output layout but with more solid string definition ( to check messages create new wallet without running daemon to get no daemon message, run daemon first popping a few hundred blocks and refresh wallet to get the out of sync message,  let it sync and refresh to get the standard output)
The bug was reported by users in linux consoles (not just putty) which i trianged.
Bug
Output after this commit
=> [Simplewallet]Prompt bug fix kept + revert to old output

external/easylogging++/easylogging++.cc, external/easylogging++/easylogging++.h
This clears all colors in Windows console
Reverts sumoprojects/sumokoin#429
=> Revert "[easylogging++] Always omit ANSI codes when colour is not supported"

src/blockchain_db/lmdb/db_lmdb.cpp
Trivial fix. I was getting left over characters from the sync bar when this line was printed on windows (not on linux) so i added the clean line ansi escape code to clear the line before it is printed.
=> [DAEMON] Small display fix

external/easylogging++/ea_config.h
- easylogging assumes certain non-standard headers and functions
- these function only exist in glibc
- compiling under linux without glibc thus broke compilation
=> [easylogging++] Disable crash log on non-glibc libraries

src/cryptonote_protocol/cryptonote_protocol_handler.inl
Only print sync complete message when out of precompiled hashes to avoid most premature triggers
=> [CORE] Fix printing sync complete message

src/p2p/net_node.inl
Unbound uses a 64 kb large character array on the stack, which leads to a stack overflow for some libc implementations only gives 80 kb in total. This changes the stack size for these threads to 1mb, which solves the segmentation fault
=> [P2P] Request a thread stack size that is large enough for unbound

src/common/dns_utils.cpp
OpenNIC DNS Servers only for more privacy https://www.opennic.org
As recently added as possible and with no logs kept declaration, added many cause they are sponsored
Added FDN's server as well in case whatever happens to OpenNIC
=> [DNS] Update DNS servers list

src/simplewallet/simplewallet.cpp
Reminder that windows wallet doesnt autolock (so decided by monero devs) to test this you have to manually lock it by typing lock on prompt
=> [SIMPLEWALLET] Limit password attempts on locked wallet to 3

src/simplewallet/simplewallet.cpp
Refresh and show balance per account after breaking locked wallet loop cause we might have received something and we wont know if we dont have autorefresh enabled or we dont enter a manual refresh
=> [SIMPLEWALLET] Refresh after breaking locked wallet loop

src/cryptonote_basic/hardfork.h
Dont freak out our users every 6 months with the the daemon popping up that needs a hardfork and an update soon. I increased it to a year which is more reasonable. Monero has set this cause they were changing pows every six months I guess they will fix this more properly as well soon
=> [CORE] Change default update time

contrib/epee/include/net/abstract_tcp_server2.inl
Should fix the restart problem on the OSes that don't handle process shutdown correctly leaving the port in use.
=> [EPEE] tcp server - set SO_LINGER instead of SO_REUSEADDR option

src/p2p/net_node.cpp, src/p2p/net_node.h, src/p2p/net_node.inl, src/rpc/rpc_args.cpp, src/rpc/rpc_args.h, tests/unit_tests/CMakeLists.txt, tests/unit_tests/node_server.cpp
As currently the daemon ignores p2p or rpc port bind failure by default
=> [P2P, RPC] Don't skip p2p or rpc port bind failure by default

contrib/epee/include/net/levin_protocol_handler_async.h
If adding a response handler after the protocol is released, they could never be cancelled again, and would end up keeping a ref that never goes away
=> [EPEE] levin: armour against some "should not happen" case

src/cryptonote_basic/miner.cpp
Checking battery status uses x86-only headers and functions. Remove this functionality to get it to build on other architectures.
=> [Miner] Fix build on FreeBSD/!x86

contrib/epee/include/int-util.h, contrib/epee/src/CMakeLists.txt, contrib/epee/src/int-util.cpp, src/cryptonote_basic/cryptonote_basic_impl.cpp, src/cryptonote_core/blockchain.cpp, tests/unit_tests/mul_div.cpp
add a 128/64 division routine so we can use a > 32 bit median block size in calculations
=> [EPEE] Support median block size > 4 GB

src/cryptonote_core/blockchain.cpp
as a safety to reject if it somehow does not get initialised
=> [Blockchain] Initialize pow to ff..ff

src/blockchain_utilities/CMakeLists.txt
Too many binaries inside the bin folder, create a new folder for the blockchain utilities and gather the utilities binaries there
=> [CMAKE] Separate blockchain utilities folder for binaries

src/cryptonote_core/cryptonote_core.cpp, src/cryptonote_core/tx_pool.cpp, src/cryptonote_protocol/cryptonote_protocol_defs.h
- tx_pool: do not divide by 0
- cryptonote: don't leave block_weight uninitialized
- protocol: initialize block_weight in block_complete_entry ctor
=> [MISC] Misc fixes (from Coverty)

src/blockchain_utilities/blockchain_import.cpp
batch_size = 100 was set for x32 archs while 20000 for x64 (this was due to a suspected db issue that couldnt handle large batches at 32 bit systems). 20000 means that sometimes even if you import from file you still have to sync normaly up to 20k blocks which is frustrating. Set batch size for all archs to 100. ~~it will take a couple of minutes more to import the entire chain  (-100 blocks worst case)~~ (it is actually faster cause it uses less ram) than having to sync 20k blocks (you can always change it with this flag --batch-size)
=> [UTILITIES] Blockchain-import batch size

external/easylogging++/easylogging++.cc, external/easylogging++/easylogging++.h
- Re-opened with Windows color fix
=> [easylogging++] Always omit ANSI codes when colour is not supported

CMakeLists.txt
- build: fix building on Windows due to _FORTIFY_SOURCE changes in MSYS2. Also, enable other hardening options that work on Windows with GCC 9.x
- Windows: enable high-entropy ASLR where available
=> [BUILD] MSYS2 build fix and hardening changes

src/cryptonote_core/cryptonote_core.cpp, src/cryptonote_core/cryptonote_core.h, src/daemon/command_parser_executor.cpp, src/daemon/command_parser_executor.h, src/daemon/command_server.cpp, src/daemon/rpc_command_executor.cpp, src/daemon/rpc_command_executor.h, src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server.h, src/rpc/core_rpc_server_commands_defs.h, utils/python-rpc/framework/daemon.py
This allows flushing internal caches (for now, the bad tx cache,
which will allow debugging a stuck deamon after it has failed to
verify a transaction in a block, since it would otherwise not try
again, making subsequent log changes pointless)
NOTE: Need PR #504 to be merged first
=> [RPC] Add a flush_cache RPC

src/hardforks/hardforks.cpp
Mainnet hardfork v9 would be triggered on Nov 19, 2019
=> [Hardfork] Set hardfork v9 heights

src/cryptonote_protocol/cryptonote_protocol_handler.h, src/rpc/core_rpc_server.cpp
Currently if a user restarts already synced daemon with `--bootstrap-daemon-address auto --no-sync` options, the daemon will immediately disable bootstrapping cause local blockchain is synced.
But it shouldn't do that if `--no-sync` is enabled.
=> [Daemon] Always use bootstrap daemon (if set) in '--no-sync' mode

cmake/GitVersion.cmake
or build won't add `release` string to binaries' version
=> [Version gen] Fix release tag detection

src/cryptonote_core/tx_sanity_check.cpp, src/cryptonote_core/tx_sanity_check.h, src/rpc/core_rpc_server.cpp, src/wallet/wallet2.cpp
that failed due to low number of txes at testnet
=> [Core, Wallet] Disable rct offset sanity check for testnet

Makefile
to build linux binary with `-DBACKCOMPAT=ON` make sure that the binary will run on systems having at least libc version 2.17
=> [Build] Add 'depends-backcompat' build option

src/wallet/node_rpc_proxy.cpp
Fix https://github.com/monero-project/monero/issues/6131
=> [Wallet] Set non-empty error string on connection failure

contrib/epee/include/net/abstract_tcp_server2.inl
This fixes rapid reconnections failing as the peer hasn't yet worked out the other side is gone, and will reject "duplicate" connections until a timeout
=> [EPEE] Close connection when the peer has done so

src/daemonizer/posix_fork.cpp
Don't leave stdout/stderr dangling on a fork
=> [Daemonizer] Fix DB corruption from child process overwrite

src/device_trezor/trezor/messages/.gitignore
Fix "Trezor protobuf messages could not be regenerated (err=1, python )" warning and errors while cmake running on the beginning
=> Fix trezor CMAKE warnings and errors

src/crypto/cn_monero_slow_hash.c, src/cryptonote_config.h, src/cryptonote_core/cryptonote_core.cpp
Its not solved but its mitigated. its due to delays of hash confirmation from "not an optimal" JIT implementation. (monero wont be improving since its now obsolete to them by turning to randomx also according to monero devs small batches of block sync size also seem to give a 30% speed increase at that area so at the end of the chain i drop the default block sync size to 1 from 50)
=> [Core] Mitigate syncing delay at the end of the chain due to JIT

src/cryptonote_config.h, src/p2p/net_node.h, src/p2p/net_node.inl
Networking connectivity improvements based on the below
https://eprint.iacr.org/2019/411.pdf
cryptonote_config.h
1. Decrease peers in handshake to mitigate high load (even though we dont have that many peers)
2. Increase default ping time out connection to compensate for nodes running in china or via vpn or with very slow connections or they are just too isolated, dont exclude them cause they delay to pong
3. Increase anchor connections to 4 to avoid isolation of nodes and create a more robust network among nodes that cover the criteria of number 2
4. Increase forget time of a failed address to a day. Dont try every one hour to reconnect to an address that most likely is dead or problematic
5. Increase block time to two days. Nodes are blocked if they are sending a bad pow, a hugely wrong …
=> [P2P] Network connectivity improvements

src/daemon/command_line_args.h, src/daemonizer/posix_fork.cpp
To prevent overwrites in case someone is using monero on the same machine as well (plus a monero to sumo change on the windows daemon service name)
=> Change output folder to sumokoin

contrib/epee/include/storages/parserse_base_utils.h, contrib/epee/include/storages/portable_storage_base.h
They are needed for logging macros even if no warning is thrown
=> [epee] add missing headers

contrib/depends/packages/openssl.mk, contrib/depends/packages/sodium.mk, contrib/depends/patches/sodium/fix-whitespace.patch
Upgrade sodium lib as per https://github.com/monero-project/monero/pull/6231 and fix openssl download location address so curl can grab it
=> [Depends] upgrade libsodium and fix openssl download location address so curl can grab it 

src/cryptonote_core/cryptonote_core.cpp
Change the default block_sync_size from 50 to 1 starting from 90% of the chain downloaded instead of 95% as per my previous commit. The delay at the end has a correlation with the distance between the end chain height and the latest checkpoint. So till we update checkpoints the furthest the chain top goes from the checkpoint the earliest the delay starts. (when i committed a month ago delay started at 96% of the chain downloaded now it starts at 94%)
=> [P2P] syncing delay at the end of chain update

contrib/epee/include/console_handler.h
Ref: https://github.com/monero-project/monero/pull/6125
=> [EPEE] fix console_handlers_binder race, wait for thread to finish

contrib/epee/include/md5_l.h, src/crypto/blake256.c
Replace all occurrences of the (potentially removed) memset with memwipe. This solves issue https://github.com/monero-project/monero/issues/6129
Note: The md5 function isn't actually used, but that epee just reimplements it whenever it needs it
=> [EPEE, CRYPTO] Replace memset with memwipe

src/common/threadpool.cpp
Ref: https://github.com/monero-project/monero/pull/6141
=> [threadpool] use std::move when taking an element off the queue

src/common/perf_timer.h
Ref: https://github.com/monero-project/monero/pull/6128
=> [perf_timer] fix pause/resume macros dereferencing too much

src/lmdb/table.h
Ref: https://github.com/monero-project/monero/pull/6093
=> [LMDB] Remove meaningless const qualifier on function type

src/crypto/cn_heavy_hash.hpp
Suppress annoying clang pragma warnings caused by the same code line on cn_heavy_hash.hpp they dont affect anything on building all archs for android wallet
=> [Android branch] suppress clang pragma warnings

src/daemon/command_parser_executor.cpp, src/daemon/rpc_command_executor.cpp, src/daemon/rpc_command_executor.h
Ref: https://github.com/monero-project/monero/pull/6095
(nice, you may print a particular tx's metadata on daemon now)
=> [daemon] add +meta print_tx parameter

src/wallet/wallet_rpc_server.cpp, src/wallet/wallet_rpc_server.h, src/wallet/wallet_rpc_server_commands_defs.h
Ref: https://github.com/monero-project/monero/pull/6102
As far as i can understand this just returns and includes the tx weight along with the rest of the necessary stuff (amount, fees, key sets etc) upon in each transfer request it does not affect tx weight calculation or sanity checks
=> [wallet_rpc_server] add tx weight in transfer commands responses

src/common/updates.cpp
Ref: https://github.com/monero-project/monero/pull/6178
AFAIK this isnt fully operational in monero as well (getting the actual updates) it just queries pulse DNS records for a new version than the one we have but apply the fix anyhow.
This pr of ours i think makes things simpler (warning in case there is a newer version)
https://github.com/sumoprojects/sumokoin/pull/663
=> [updates] fix source code URL on _WIN32

contrib/epee/src/net_ssl.cpp
Ref: https://github.com/monero-project/monero/pull/6184
(tested - builds fine on MSYS)
=> [net_ssl] load default certificates in CA mode on Windows

src/cryptonote_config.h, src/cryptonote_core/cryptonote_core.cpp, src/p2p/net_node.inl
On considering the latest commit to improve syncing at the end of chain https://github.com/sumoprojects/sumokoin/pull/621
since the delay starts from approximately the last checkpoint (block hashes must be checked from then on causing the delay) there is no point in moving the default block syncing default count change (from 50 to 1) backwards all the time. 
Remove the percentage and make the change to always start from the last checkpoint.
Also revert worker p2p thread count to 10 (it slows down hash verification on low end machines)
=> [p2p] improve syncing

src/daemon/rpc_command_executor.cpp
Daemon status command now prints the current blockchain size, in MB, at blockchain info field
=> [daemon] status now prints current blockchain size

src/daemon/command_parser_executor.cpp, src/daemon/command_parser_executor.h, src/daemon/command_server.cpp, src/daemon/rpc_command_executor.cpp, src/daemon/rpc_command_executor.h
Typing  `disk ` on the daemon displays the blockchain db size on disk as well as the remaining disk space on the drive the chain is located.
This goes in unison with https://github.com/sumoprojects/sumokoin/pull/687
=> [daemon] new command 'disk'

.gitignore
include in gitignore the pyc files that are build from the py files at src/device_trezor/trezor/tools/py2backports/ folder
=> [gitignore] include trezor compiled python files after building

contrib/depends/patches/sodium/fix-whitespace.patch
Add a whitespace that was missing giving a malformed patch error on cross compiling
=> [build] fix libsodium patch

src/blockchain_utilities/CMakeLists.txt
This pr including this https://github.com/sumoprojects/sumokoin/pull/669 , this https://github.com/sumoprojects/sumokoin/pull/668 and this https://github.com/sumoprojects/sumokoin/pull/667 fix all cross compiling issues. 
Produced perfect, statically linked, windows binaries from linux terminal (including the exe files of the blockchain utilities folder).
This pr also fixes the blockchain utilities windows binaries linker issues when built statically from MSYS on Windows
=> [building] fix static cross compile for windows bins

src/crypto/cn_heavy_hash_soft.cpp
Builds in all archs now properly (32 & 64 bit)
=> [crypto] proper fix for _rotr on cn_heavy

src/wallet/wallet2.cpp
Ref: https://github.com/monero-project/monero/pull/6194
=> [wallet2] Better error conditions when restoring with wrong keys

.github/workflows/build.yml, .travis.yml
Since we are not using travis at each branch for various reasons (I updated travis in this commit to be concurrent with monero's anyhow), this adds github's workflow automated process for automated building and initial testing upon each PR or code change (workflow configuration as per monero's latest without building the tests folder). I tested it in random PRs it is working perfectly and imo its better than travis
=> [github] Install workflow build and test process 

src/wallet/wallet_rpc_server.cpp
Ref: https://github.com/monero-project/monero/pull/6203
=> [wallet rpc] remove unused variable 'ptx'

src/cryptonote_core/blockchain.cpp, src/cryptonote_core/blockchain.h, src/cryptonote_core/cryptonote_core.cpp, src/cryptonote_core/cryptonote_core.h, src/daemon/command_parser_executor.cpp, src/daemon/command_server.cpp, src/daemon/rpc_command_executor.cpp, src/daemon/rpc_command_executor.h, src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server_commands_defs.h
Ref: https://github.com/monero-project/monero/pull/6211 + small amendment at core_rpc_server_commands_defs.h cause flush cache rpc command is not a public request/response
=> [rpc] add bad-blocks to flush_cache RPC

src/cryptonote_protocol/cryptonote_protocol_handler.inl
Ref: https://github.com/monero-project/monero/pull/6219
(There is a good chance this bug fix might improve the end of chain sync delay more)
=> [Core] Fix time comparison math (cryptonote protocol handler)

src/rpc/core_rpc_server.cpp
Ref: https://github.com/monero-project/monero/pull/6242
=> [rpc] drop the obsolete and wrong 'unpruned size' log

contrib/depends/funcs.mk
Ref: https://github.com/monero-project/monero/pull/6255
Ref: https://github.com/zcash/zcash/pull/2700
This only happens when cross building on desktop envs like windows or macos and there are more unrestricted pathnames all over depends packages but since monero added this lets added as well
=> [depends] empty spaces in PATH variable cause build failure

src/rpc/core_rpc_server.cpp
This PR ( ref: https://github.com/monero-project/monero/pull/6259 ) partially reverts this https://github.com/monero-project/monero/pull/5964 as reported by this issue https://github.com/monero-project/monero/issues/6258
In our case it serves us fine cause we had from the beginning an empty string in the response for miner_tx_hash in the root field, although the miner_tx_hash shows above at block header. Now we get response for the miner_tx_hash in the root field as well as shown at the images below
Before
After
=> [rpc] fill miner_tx_hash at root field of on_get block rpc call

src/common/util.cpp, src/cryptonote_protocol/cryptonote_protocol_handler.inl
Partial ref: https://github.com/monero-project/monero/pull/6058
We dont need the extra help message cause we have our own format on lock screen but we do need the split line with /n on string printing redefinition.
(Plus a small typo fix)
=> [utils] split line(string) with '\n'

contrib/depends/packages/native_cctools.mk, contrib/depends/packages/qt.mk
This is a minor fix which was supposed to be more complicated in order to upgrade Qt since the version is very old and zlib was required even though monero took it out of depends and Qt has to get it from the system now (upgrade was getting messy though https://github.com/sumoprojects/sumokoin/pull/696 for such an unimportant fix, Qt is only needed by sumokoin and monero for some tools and translations). 
Anyhow fix a minor mistake in the current Qt configuration and update clang dep as well to a new and more stable version that doesnt require cctools hacks to build ref: bitcoin/bitcoin@1de8c06
=> [depends] Fix Qt and update clang

contrib/epee/src/net_ssl.cpp
At the moment master wont build at Xenial cause Xenial hosts boost 1.58 by default and ssl::context::tls is not declared on this boost version. This is a "smart and stupid", at the same time, workaround, since monero guys disallowed sslv2 and sslv3 as well as tlsv1 and tlsv2 with ssl flags so as to return tls version 1.2 and up, we set sslv23 by default which is ok with boost 1.58 and we know its wrong and the flags below make sure its upgraded to tlsv1.2 that we wanted anyhow.
(Dont mind the failed windows check, github failed to setup msys and aborted the build i built on mingw locally its fine)
=> [epee]TLS1.2 workaround-boost 1.58 (Xenial build)

src/p2p/net_node.inl
If a remote node has a different network id than the one hardcoded dont wait for the fail attempts to reach the critical number in order to block it. Ban/block it right away on first fail, the network id wont magically change in a few minutes on the next connection attempt. That remote node was compiled on purpose with a different network id and is most likely intentionally (or unintentionally - if it was compiled for testing purposes as such) spamming our network
=> [p2p] If remote node has a different net id ban right away

contrib/epee/include/net/abstract_tcp_server2.inl
Ref: https://github.com/monero-project/monero/pull/6244
=> [abstract_tcp_server2] guard against negative timeouts

contrib/epee/src/hex.cpp, tests/unit_tests/epee_utils.cpp
Ref: https://github.com/monero-project/monero/pull/6360 (as merged by luigi1111 on xmr's 0.15 branch for their upcoming release. If there are amendments when this is merged on xmr's master they will be included)
=> [epee] Fixed string_ref usage bug in epee::from_hex::vector

src/wallet/wallet2.cpp
Monero uses a selection of decoys method by picking 50% of their "chaff" decoys from their chain history as well as 50% from the last 1.8 days since Monero is constraint by the Miller et al traceability analysis paper https://arxiv.org/pdf/1704.04299.pdf which deduced that at least 50% of the decoys 
should come from the "recent" chain as per the empirical analysis of Monero users usage of the blockchain. 
That paper is based on a chain like Monero which has a major part of its chain early history based on txs exclusively on Ring size 1 which means it can always be subject to "chain-reactions" traceability attacks as described on the MRL paper here https://web.getmonero.org/resources/research-lab/pubs/MRL-0007.pdf
Monero did a great job with picking the triangular distribution algorithm …
=> [wallet2] improve decoy outputs selection

src/simplewallet/simplewallet.cpp
Outputs before being spent are being checked for their age and if they are  "old" a warning pops "Transaction spends more than one very old output. Privacy would be better if they were sent separately." . Actually monero devs commented `// 30 days` next to the constant but actually `OLD_AGE_WARN_THRESHOLD (30 * 86400 / DIFFICULTY_TARGET)` is not days its the number of blocks emitted in 30 days. The OLD_AGE_WARN_THRESHOLD is inversely proportional to the difficulty target so in order to keep the output (number of blocks) same as Monero since the denominator is half in sumo (4 minutes instead of 2) the numerator  should be double (60 days)
[Actually the warning altogether has little value at the moment because it has validity for a sufficient rate of included txs per block while we dont …
=> [simplewallet] update tx old age warning threshold

src/cryptonote_config.h
🤦‍♂ CRYPTONOTE_DEFAULT_TX_SPENDABLE_AGE  entered twice (its on line 55)
=> [config] Delete double entry

CMakeLists.txt, src/wallet/wallet2.cpp
Revert the fix on wallet2 for the warning that trusted_daemon variable may be used uninitialized cause the trusted daemon logic is defined in a messy way so instead of rewritting it just silence it on cmake.
Added as well a flag to not emmit warnings that may arise from flags not recognised between different gcc versions (-Wno-unknown-warning)
=> [wallet2] revert the warning fix and silence it in cmake

CMakeLists.txt
The linker flag's if clause, for position-independent executable (pie), was miswritten causing static build with make release-static build on xenial failing.
A clean 16.04 instance needs libusb-1.0-0-dev , libudev1 and libudev-dev installed otherwise build fails. 
(This has nothing to do with cross compile built binaries compatibility with old linux versions but only with make release-static on 16.04 natively. Best way to make cross compile binaries for linux to be compatible with old linux distro releases is to build them at the most clean and old linux version available rather than start patching libraries like monero did with sodium. Cross built linux binaries on 16.04, for example, work with 16.04 and 18.04 however cross built linux binaries on 18.04 are not backward compatible to …
=> [cmake] fix for building static on ubuntu xenial and old linux versions

src/daemon/rpc_command_executor.cpp
Windows doesnt like revealing file size while Linux has not problem with that.
Omit printing current db size on windows on "status" and the recently added "disk" calls.
Unconvential way of checking if daemon is running on windows but it was the easiest i could think of :)
=> [daemon] Modify show db_size

src/blockchain_utilities/CMakeLists.txt
Due to a recent msys2 bug with  -D_FORTIFY_SOURCE and -fstack-protector flags (Ref: https://github.com/msys2/MINGW-packages/issues/5868) libssp dynamic library (dll) was missing (not statically linked) when trying to run  blockchain utilities exe files as it now needs to add -fstack-protector explicitely to these EXEs for -lssp to be added. So just link lssp directly to these binaries
=> [MSYS2] Fix broken lib linker

src/net/i2p_address.cpp, src/net/tor_address.cpp, tests/unit_tests/net.cpp
Ref: https://github.com/monero-project/monero/pull/6285
~~(I am not adding the changes on net unit tests cause they fail to compile and even if i fix or comment out the code that fails to compile (due to a static assert catch on epee's portable storage) newly added net unit tests fail. I guess they ll have to fix it)~~  Fixed with https://github.com/monero-project/monero/pull/6407
=> [net] fix incorrect less operator for top/i2p addresses

src/p2p/net_node.inl
Spare us the time and resources checking for seed nodes by DNS resolving hardcoded addresses which are not updated regularly anyhow.  
Use the hardcoded seed list directly. Plenty of seed nodes that are regulary checked and updated.
Also add in the same PR monero's https://github.com/monero-project/monero/pull/6283 
(It resets the connection list to zero by ignoring the first added node which is always a seed (to grab its peerlist) and a new connection)
=> [p2p] use the hardcoded seed nodes directly + fix off by one adding fallback peers

src/common/threadpool.cpp, src/cryptonote_basic/miner.cpp, src/cryptonote_config.h, src/p2p/net_node.inl
I was considering increasing the p2p threads initially when noticed that the stack size was predetermined to 512Kb instead of 1 Mb in order to accomodate macOS which has half the default stack size compared to Linux and Windows (even iOS's is 1 Mb).
So remove it from config and set it explicetely to the places that this variable was used.
Time and testing will tell if this speeds up things at all cause even with half the stack size there was no overflows but in any case this is the correct way to address the stack size (1 Mb for all OS except for macOS)
=> [core] increase default stack size to normal size

src/simplewallet/simplewallet.cpp, src/wallet/ringdb.cpp, src/wallet/wallet2.cpp
Ref: https://github.com/monero-project/monero/pull/6288
(with a minor change in wording as we have no txs with 0 mixin)
That's a good catch by moo what he actually did is figure out that since keys and data are two separate entities in the stored rings table and this is a stream cipher, they need to be combined with a different initialisation vector.
We keep the authentication tag for ciphered data same we dont mind.
Very nice catch. Because of such things Monero is unbeatable in privacy
=> [wallet] do not erase rings on tx failure, better iv selection and wording update

src/cryptonote_core/cryptonote_core.cpp, src/cryptonote_core/cryptonote_core.h, src/cryptonote_core/tx_pool.cpp, src/cryptonote_core/tx_pool.h, src/cryptonote_protocol/cryptonote_protocol_defs.h, src/cryptonote_protocol/cryptonote_protocol_handler.h, src/cryptonote_protocol/cryptonote_protocol_handler.inl, tests/core_proxy/core_proxy.h, tests/unit_tests/node_server.cpp
Ref: https://github.com/monero-project/monero/pull/6214
That's a nice one, it forces the local tx pool of a newly synced node to get all txs on global txpool by sending to a random peer a small list of the txs it has already so forcing the random remote to relay back the txs the local doesnot have in its pool
=> [cryptonote_protocol] request txpool contents when synced

src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server.h
Ref: https://github.com/monero-project/monero/pull/6260
Quote
_This allows RPC coming from the loopback interface to not have
to pay for service. This makes it possible to run an externally
accessible RPC server for payment while also having a local RPC
server that can be run unrestricted and payment free._
Unquote
=> [rpc] add --rpc-payment-allow-free-loopback

src/simplewallet/simplewallet.cpp, src/simplewallet/simplewallet.h
Ref: https://github.com/monero-project/monero/pull/6301
Quote
_The warning about spending more than one output with similar creation
time was skipped if print-ring-members was not set, and it defaults to
false, which means most people probably aren't getting this warning if
they spend correlated outputs._
_Reported by SeventhAlpaca._
Unquote
=> [simplewallet] warn about correlations if print-ring-members is not set

src/wallet/wallet2.cpp
Ref: https://github.com/monero-project/monero/pull/6304
Quote
_The backward compatibility code was always setting it to 1
in modern wallets since store_tx_keys was not present and thus
assumed to be 1 by default._
_Reported by SeventhAlpaca_
Unquote
=> [wallet2] fix store-tx-info loading

contrib/depends/funcs.mk
We previously removed that depends fallback address, leading to bitcoin's repo, cause it was obsolete.
Remove this reference as well (when cross building it gives curl a bad time trying to find it when for some reason connection to an official repo fails and ends the building)
=> [depends] remove obsolete fallback address reference

.github/workflows/build.yml
Ref: https://github.com/monero-project/monero/pull/6411
Timing out while getting dependencies is a very common failling reason for linux workflows building
=> [workflows] retry on apt failure / increase timeout

src/cryptonote_basic/verification_context.h, src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server_commands_defs.h, src/rpc/daemon_handler.cpp, src/wallet/wallet2.cpp, tests/functional_tests/transfer.py
Ref: https://github.com/monero-project/monero/pull/6286
=> [core] drop unused verification_context::m_not_rct field

external/easylogging++/easylogging++.h
Fixed the warnings (build logs on workflow checks for both ubuntu and mingw build for windows confirm that as well). We either merge this now or we can merge it along with https://github.com/monero-project/monero/pull/6332 if it gets approved after review
The implementation was bad from monero side it is supposed to be
```
#if defined(__EMSCRIPTEN__)
#else
#endif
```
not 
```
#if defined(__EMSCRIPTEN__)
#endif
```
=> [easylogging++] add emscripten support

contrib/epee/src/wipeable_string.cpp, tests/unit_tests/wipeable_string.cpp
Ref: https://github.com/monero-project/monero/pull/6335
It strips whitespaces and line breaks from seed, nice
=> [epee] wipeable_string: split - treat CR, LF and Tabs as separators

src/cryptonote_basic/account.cpp, src/cryptonote_basic/cryptonote_format_utils.cpp, src/cryptonote_config.h, src/device/device_default.cpp, src/multisig/multisig.cpp, src/ringct/bulletproofs.cc, src/rpc/rpc_payment.cpp, src/wallet/ringdb.cpp, src/wallet/wallet2.cpp
Ref: https://github.com/monero-project/monero/pull/6338
Just moves all crypto hash function domain separators to cryptonote_config.h for easier reference and avoid collisions by chosing same by mistake in the future if more are added.  (nothing too important)
=> [crypto] Hash domain separation

src/simplewallet/simplewallet.cpp
This notification warns us when we use an encrypted payment id and suggests to use subaddresses for more privacy instead.
It keeps on appearing annoyingly  (even it was fixed by monero in the past) at random transactions. I think its the way the if clause is defined 
```
if (payment_id8 != crypto::null_hash8)
message_writer() <<
tr("NOTE: this transaction uses an encrypted payment ID: consider using subaddresses instead");
```
check if dummy payment id (payment_id8) is different from the dummy crypto::null_hash8 (always created for tx uniformity) which would mean that there is a user defined encrypted payment id. Its kind of sloppy. I wont be changing anything just bring this notification message permantly to be shown once on intro messages and get over and done with it
the warning below …
=> [simplewallet] Change notification for encrypted payment id

src/rpc/CMakeLists.txt, src/rpc/bootstrap_daemon.cpp, src/rpc/bootstrap_daemon.h, src/rpc/bootstrap_node_selector.cpp, src/rpc/bootstrap_node_selector.h, src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server.h, tests/unit_tests/CMakeLists.txt, tests/unit_tests/bootstrap_node_selector.cpp
This is a very good one, it optimizes the selection of nodes for bootstrapping improving the overall Sumokoin (and Monero) experience
Ref: https://github.com/monero-project/monero/pull/6357
**Quote**
_Improved public node selection algo used in Simple mode/---bootstrap-daemon-address auto._
_1. In-memory public nodes cache storing up to N (N=1000 by default) entries
2. If the cache doesn't have at least one good public node (having fails count == 0):
i. Get public nodes from P2P_
_ii. Add new white public nodes to cache with initial fails count = 0
iii. Add new gray public nodes to cache with initial fails count = 1
iv. Truncate the cache to N public nodes, keep the nodes having lower fails count
3. Select most stable public node (sorted by fails count), if there are multiple - choose a …
=> [daemon] auto public nodes - cache and prioritize most stable nodes

contrib/epee/include/hex.h, contrib/epee/include/storages/parserse_base_utils.h, contrib/epee/include/string_tools.h, contrib/epee/src/hex.cpp, src/rpc/rpc_args.cpp, src/serialization/json_object.cpp, src/serialization/json_object.h, src/wallet/wallet2.cpp, tests/unit_tests/epee_utils.cpp
Ref: https://github.com/monero-project/monero/pull/6351
(Dont mind the large diff on wallet2.cpp the actual change on that file is a single line, I ve started using Atom to edit so as to autocorrect rogue tabs and spaces at each file i process)
**Quote**
_The initial reason for the change was hex->bin conversion in the ZMQ JSON-RPC server required a temporary std::string for each attempt. The individual commits should explain the other changes.
This move isn't strictly necessary to improve performance, but does it make easier on the compiler (less code in the header AND declared in a header with less overhead). The latter is useful because the ZMQ JSON code can (eventually) just include hex.h instead of the more expensive string_tools.h._
**Unquote**
=> [epee] improve hex->bin Conversion

src/rpc/message.cpp, tests/unit_tests/CMakeLists.txt, tests/unit_tests/zmq_rpc.cpp
Ref: https://github.com/monero-project/monero/pull/6361
New unit test adjusted for sumo
Quote
_The ZMQ JSON-RPC fails to ensure that the `method` field is a string._
Unquote
=> [zmq json-rpc] bug fix in ZMQ JSON-RPC method field

src/cryptonote_protocol/levin_notify.cpp, tests/unit_tests/levin.cpp
Ref: https://github.com/monero-project/monero/pull/6381
Quote
_Transactions are temporarily queued per connection for diffusion, which can leak receive/processing order of two different connections._
Unquote
=> [cryptonote_protocol] fix receive order leakage with tx fluffing

src/blockchain_db/lmdb/db_lmdb.cpp
Ref: https://github.com/monero-project/monero/pull/6384
Quote
_If a db resize happened, the txpool meta cursor might be stale,
and was not being renewed when necessary.
It would cause this SEGSEGV:_
_in mdb_cursor_set ()
in mdb_cursor_get ()
in cryptonote::BlockchainLMDB::get_txpool_tx_blob(crypto::hash const&,_ _std::__cxx11::basic_string<char, std::char_traits, std::allocator >&, cryptonote::relay_category) const ()
in cryptonote::tx_memory_pool::get_transaction(crypto::hash const&, std::__cxx11::basic_string<char, std::char_traits, std::allocator >&, cryptonote::relay_category) const ()_
_in cryptonote::t_cryptonote_protocol_handlercryptonote::core::handle_notify_new_fluffy_block(int, epee::misc_utils::struct_initcryptonote::NOTIFY_NEW_FLUFFY_BLOCK::request_t&, …
=> [lmdb] fix race crash using a stale cursor

src/simplewallet/simplewallet.cpp, src/simplewallet/simplewallet.h
Move another annoying warning and make it a notification in wallet's opening intro.
We do not have the amount of txs of monero or the amount of users that use their wallet that frequently and we have a much higher ring size, so old outputs more than 2 months old (as per our limit) are frequent in almost all users wallets and the warning gets constant and obnoxious upon each tx for all these reasons. Pushing the limit backwards wouldnt help that much. So notify users on wallet's into of better spending old outputs separately if they are concerned about extreme privacy and that's all
=> [simplewallet] amend old outputs spent warning into a notification

CMakeLists.txt
unique_ptr needs a destructor defined and implemented for each class, and making sure they are defined as virtual for inheritance.
That goes for this one https://github.com/sumoprojects/sumokoin/blob/dev/src/rpc/bootstrap_daemon.h#L81 (bootstrap_daemon.h)
Anyhow there is a complex way of fixing this by restructing the classes (derived classes and so on) to make clang happy (clang only warns about it not gcc) but just shut clang up for this case (and reenable it if monero ever decides to take care of this)
=> [cmake] silence unique_ptr non-virtual destructor warning

CMakeLists.txt
The idea was borrowed from a recently opened monero pull request (strange that noone thought of adding automatic finding of ccache till now).
I implemented it a bit differently, the guy who pushed that to monero (#6452 - i am not referencing it directly cause i dont know if they are going to merge it) for some reason created a cmake file with it which he included it in cmakelists with `include`. I just added the code directly in there.
ccache can be installed with `apt-get install ccache` on ubuntu and on mingw with `pacman -S mingw-w64-x86_64-ccache`
Why do we need ccache? from https://ccache.dev/
**Quote**
_If you ever run make clean; make, you can probably benefit from ccache. It is common for developers to do a clean build of a project for a whole host of reasons, and this throws away …
=> [cmake] add finding ccache automatically for faster (re)building

src/cryptonote_protocol/cryptonote_protocol_handler.inl, src/daemon/command_parser_executor.cpp, src/daemon/command_parser_executor.h, src/daemon/command_server.cpp, src/daemon/rpc_command_executor.cpp, src/daemon/rpc_command_executor.h, src/p2p/net_node.inl, src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server.h, src/rpc/core_rpc_server_commands_defs.h
**Various code fixes, display improvements and format fixes**
1. [p2p] print amount of seconds when we ban a node 
2. [p2p] mention on logs that we ban peers with different network id as soon as they appear when dropping that connection with the different id (plus a small comment change on a seed description)
3. [daemon] make printing the banned ip list along with the time remaining nicer (on daemon "bans" command)
4. [rpc] we dont need the "update" rpc call. Spare us the compile time and resources. Updating of binaries from a remote server is still experimental in Monero. The only think working in xmr is checking if a newer version exists (which can be done in several other easier ways than keeping a running remote server just for this constantly)
5. [cryptonote_protocol] Look what was …
=> [core] code fixes, display improvements and format fixes

README.md
there is no libzmq package in FreeBSD there are libzmq1, libzmq2, libzmq3, libzmq4.
Add the latest version
=> [README] Fix FreeBSD required dependencies

src/simplewallet/simplewallet.cpp, src/wallet/wallet2.cpp, src/wallet/wallet2.h
**Edit-Update: they decided that invisible funds on an invisible account that can easily be forgotten and cannot be accessed without a sweep_account command is a good thing to have. They created the one-off command for a large index bug that they couldnt recollect the actual bug's details (at least that was the excuse they gave me after they were insisting that the feature was created for retreiving funds when they are sent by mistake at a random monero address and i kept on questioning how this absurdity is possible 😄 ). Discussion here:**
Ref: https://github.com/monero-project/monero/pull/6450
I ll bring in the https://github.com/monero-project/monero/pull/6449 for the sweep_account command though which maybe useful for other cases
**[DONT MERGE] I've tested and it is buggy when you …
=> [simplewallet] new "address one-off <major> <minor>" command [merge - i ll push a patch]

src/blockchain_db/blockchain_db.cpp, src/blockchain_db/blockchain_db.h, src/crypto/duration.h, src/cryptonote_basic/verification_context.h, src/cryptonote_config.h, src/cryptonote_core/cryptonote_core.cpp, src/cryptonote_core/tx_pool.cpp, src/cryptonote_protocol/cryptonote_protocol_defs.h, src/cryptonote_protocol/cryptonote_protocol_handler.h, src/cryptonote_protocol/cryptonote_protocol_handler.inl, src/cryptonote_protocol/enums.h, src/cryptonote_protocol/levin_notify.cpp, src/cryptonote_protocol/levin_notify.h, src/p2p/net_node.h, src/p2p/net_node.inl, src/p2p/net_node_common.h, src/rpc/core_rpc_server.cpp, src/rpc/daemon_handler.cpp, src/rpc/daemon_handler.h, tests/core_tests/block_validation.cpp, tests/core_tests/block_validation.h, tests/core_tests/chaingen.h, tests/core_tests/chaingen_main.cpp, tests/core_tests/tx_pool.cpp, tests/core_tests/tx_pool.h, tests/unit_tests/levin.cpp
Fully enable dandelion++ support to sumokoin public networks (many many thanks to vtnerd)
Dandelion++ is a brilliant tx origin obfuscation method proposed by Cornell University in 2017-2018 as described here https://arxiv.org/abs/1805.11060
Full papers here
original paper: https://arxiv.org/pdf/1701.04439.pdf
final paper: https://arxiv.org/pdf/1805.11060v1.pdf  
It is fully backwards compatible, it does not need an HF and it defaults to true however the more "honest" nodes running it, the greater and more secure the obfuscation which means next release should be marked as mandatory.
To test if dandelion is functional on your sumo node just type on your daemon 
`set_log +net.p2p.tx:debug`
Ref: https://github.com/monero-project/monero/pull/6314
=> [cn_protocol+rpc+p2p] Dandelion++ support to sumokoin public networks

src/daemon/core.h
Just print them. Logs are oversized already
=> [daemon] dont bring ascii logo that dont belong to global logs into them

src/cryptonote_core/cryptonote_core.cpp, src/cryptonote_core/cryptonote_core.h
Ref: https://github.com/monero-project/monero/pull/6468
This follows the recent removal of seed nodes dns checking to improve node startup speed by going directly to hardcoded seeds.
I was planning to comment out the checkpoints dns checking, the good old fashioned sumogr way, but do it properply since xiphon pushed a pr for it on monero
**Quote**
_Takes too long to fetch DNS checkpoints on startup.
It will check DNS checkpoints a few moments later in background (from p2p connection thread on a new block/tx).
Will still do the check on startup If a user enforced DNS checkpoints (--enforce-dns-checkpointing)._
**Unquote**
=> [cryptonote_core] skip dns checkpoints on startup if not enforced

contrib/epee/include/net/abstract_http_client.h, contrib/epee/include/net/http_client.h, contrib/epee/include/storages/http_abstract_invoke.h, contrib/epee/include/syncobj.h, contrib/epee/src/CMakeLists.txt, contrib/epee/src/abstract_http_client.cpp, src/wallet/message_store.cpp, src/wallet/message_store.h, src/wallet/message_transporter.cpp, src/wallet/message_transporter.h, src/wallet/node_rpc_proxy.cpp, src/wallet/node_rpc_proxy.h, src/wallet/wallet2.cpp, src/wallet/wallet2.h, src/wallet/wallet_rpc_payments.cpp, tests/fuzz/http-client.cpp
Ref: https://github.com/monero-project/monero/pull/6332
**Quote**
- Add contrib/epee/include/net/abstract_http_client.h which http_client.h extends.
- Replace simple_http_client with abstract_http_client in wallet2, message_store, message_transporter, and node_rpc_proxy.
- Skip code incompatible with webassembly using #if defined __EMSCRIPTEN__ directives.
- Add ability to import and export wallet file buffers in wallet2 instead of using file system.
Code and collaboration credits: moneromooo, endogenic, mymonero
**Unquote**
=> [wallet2] allow wallet2.h to run in WebAssembly

tests/unit_tests/epee_utils.cpp
This is partial from https://github.com/monero-project/monero/pull/6359
_Fixed string_ref usage bug in epee::from_hex::vector_
The bug was fixed in our code in a past commit, add the unit_tests part now as well
Of course boost::string_ref (and many of the epee tools) could have been replaced with C++17 STL , in this case std::string_view
=> [unit_tests] string_ref test

src/wallet/api/wallet2_api.h, src/wallet/api/wallet_manager.cpp
Ref: https://github.com/monero-project/monero/pull/6415
**Quote**
_GUI version and build tag may differ from libwallet ones (i.e. monero (sumokoin) core version used to build GUI).
The commit provides a way to check updates based on GUI version and build tag._
**Unquote**
=> [wallet_api] checkupdate - optional version and buildtag params

tests/functional_tests/make_test_signature.cc, tests/functional_tests/rpc_payment.py
Ref: https://github.com/monero-project/monero/pull/6433
fixes an occasional failure by constraining timestamps
=> [functional_tests] ensure signed timestamps are fresh

src/cryptonote_core/cryptonote_core.cpp, src/cryptonote_core/cryptonote_core.h, src/cryptonote_core/tx_pool.cpp, src/cryptonote_core/tx_pool.h, src/rpc/core_rpc_server.cpp, tests/functional_tests/functional_tests_rpc.py, tests/functional_tests/transfer.py, tests/functional_tests/txpool.py, tests/libwallet_api_tests/main.cpp, tests/unit_tests/bootstrap_node_selector.cpp, utils/python-rpc/framework/daemon.py
Ref: https://github.com/monero-project/monero/pull/6445
Mostly brought in for code continuity cause there was a bit of restructuring
(fuctional tests are not fully enabled in sumo)
(fixed a port number on python rpc and on some tests as well while i was at it)
+
Ref: https://github.com/monero-project/monero/pull/6477
Quote
_Testing behavior of Dandelion++ via the restricted port is not possible currently - the stem/fluff mode changes the behavior of the node and is selected randomly._
Unquote
=> [dandelion++] dandelion++ functional tests

src/simplewallet/simplewallet.cpp
otherwise we 'll have people looking for the funds they stored at an one off with an enormous major index (or way beyond the lookahead value) that they didnt store...
=> [simplewallet] restrict one-off subaddress to current accounts and indices

contrib/depends/packages/native_cdrkit.mk
the currently link was failing on and off get it from fedora project repo which is consistent
=> [depends] update cdrkit link

tests/unit_tests/output_selection.cpp
We increased the range of the end of chain output selection and introduced randomness in picking through that range. That means that for edge cases unit test for output selection fail
`Expected: (fabsf(selected_ratio - chain_ratio)) < (0.025f), actual: 0.0263155 vs 0.025`
Increase the right hand side of the inequality to include almost all edge cases.
(Due to the randomness 0.028 is more or less empirical it might need amendement but i think it will cover almost all cases)
=> [unit_tests] fix output selection test

src/daemonizer/windows_service.cpp, src/gen_ssl_cert/gen_ssl_cert.cpp
Cross compiling on mingw caught it otherwise noone would have spot it. 
```
/usr/share/mingw-w64/include/winsock2.h:15:2: warning: #warning Please include winsock2.h before windows.h [-Wcpp]
#warning Please include winsock2.h before windows.h
```
In `gen_ssl_cert.cpp`
`include_base_utils.h` drags in `easylogging++.h`  which is **ANCIENT** and it has a shitty construction here 
```
#if ELPP_OS_UNIX
#elif ELPP_OS_WINDOWS
#endif  // ELPP_OS_UNIX
```
same case more or less on windows_service.cpp (coming from a not all inclusive ifdef in string_tools.h)
windows.h includes winsock.h by default. winsock.h and winsock2.h do not coexist. If winsock2.h is included first, it disables winsock.h, and all is good. But if winsock.h is included first, winsock2.h fails to compile, because it redeclares a …
=> [winsocks] fix for mingw (windows) building

.github/workflows/build.yml
From github man page
https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
_Supported runners and hardware resources
Each virtual machine has the same hardware resources available.
2-core CPU
7 GB of RAM memory
14 GB of SSD disk space_
=> [workflows] decrease building threads to 2

src/wallet/wallet2.cpp
its the account that you are sweeping that has no unlocked balance not the entire wallet
=> [wallet2] correct no unlocked balance error message

src/simplewallet/simplewallet.cpp, src/wallet/wallet2.cpp, src/wallet/wallet2.h
mooo fixed it properly by fixing the expansion of all indices all they way down to the one-off.
Ref: https://github.com/monero-project/monero/pull/6485
So no need to restrict the one-off any more :)
This PR applies the fix and reverts https://github.com/sumoprojects/sumokoin/commit/489a6e0b7e736efc98007b7b0a11ddecd330c6f4
Also no need for https://github.com/sumoprojects/sumokoin/pull/871 and https://github.com/sumoprojects/sumokoin/pull/872 which are closed
=> [wallet2] fix subaddress expansion when receiving sumo

src/cryptonote_config.h
@quangvu3 please remember, before each release, when you add a new checkpoint on checkpoints.cpp to update this as well
(it's to tell the daemon where the fast sync ends and reduce the block sync size from 50 to 1)
=> [checkpoints] Fix last checkpoint on config

src/rpc/daemon_handler.cpp
Ref: https://github.com/monero-project/monero/pull/6486
Accidentally deleted by vtnerd when restructuring zmq json-rpc
=> [ZMQ JSON-RPC] fix ZMQ JSON-RPC endpoint names for raw tx

src/cryptonote_core/tx_pool.cpp
makes silly g++ 5.4.0 happy by removing the confusion for const auto relay_method var so as it compiles on xenial
Pushed the same to monero
=> [txpool.cpp] rename var to fix for old g++ version (xenial default)

src/cryptonote_core/blockchain.cpp
make it a bit less creepy. Yes, it's important but the multiline printout scares users
=> [blockchain] make adding alt blocks print out more compact

src/wallet/wallet2.cpp
Latest clang was warning about it and it is absolutely right
```
warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
m_http_client(std::move(http_client_factory->create())),
```
https://developers.redhat.com/blog/2019/04/12/understanding-when-not-to-stdmove-in-c/
=> [wallet2] Replace std::move with boost::move to avoid prevention of copy elision

contrib/epee/include/console_handler.h, contrib/epee/include/net/abstract_tcp_server2.inl, contrib/epee/include/net/http_server_impl_base.h, contrib/epee/include/storages/levin_abstract_invoke2.h, src/blockchain_utilities/blocksdat_file.h, src/blockchain_utilities/bootstrap_file.h, src/checkpoints/checkpoints.cpp, src/device_trezor/trezor/transport.cpp, src/rpc/rpc_args.cpp, src/simplewallet/simplewallet.cpp, src/wallet/wallet2.cpp
Besides the practice of declaring the boost bind placeholders (_1, _2, ...) in the global namespace is deprecated (and need `boost::placeholders::` before them) everything else is fine
=> [boost] make sumo compile with boost latest (1.73.0)

src/wallet/message_store.cpp
it scares people who dont know what it is when they run rpc wallet and it's more of a message than an error
https://github.com/monero-project/monero/pull/6484
=> [mms] turn error to message if "no message store file is found"

src/crypto/oaes_lib.c
ftime is deprecated and will be removed from c's gnu library soon, latest ubuntu versions emit warnings about it (20.04)
http://man7.org/linux/man-pages/man3/ftime.3.html
replace it at oaes_lib.c with `gettimeofday` for all os (was used for freebsd only)
=> [crypto] ftime is deprecated use gettimeofday

contrib/epee/src/net_ssl.cpp, src/simplewallet/simplewallet.cpp
Since we are removing protobuf with #888 , change the only other reason cross compiling for mingw needed posix implementation and required updating and turning into g++ and gcc posix alternatives on the system. This is not required any more. Happy times
=> [std] replace std::this_thread::sleep instances with its boost equivalent

contrib/epee/include/byte_slice.h, contrib/epee/src/byte_slice.cpp, src/net/zmq.cpp, src/net/zmq.h, src/rpc/daemon_handler.cpp, src/rpc/daemon_handler.h, src/rpc/message.cpp, src/rpc/message.h, src/rpc/rpc_handler.h, src/rpc/zmq_server.cpp, tests/unit_tests/net.cpp
Ref: https://github.com/monero-project/monero/pull/6350
**Quote**
_Sending JSON response on the ZMQ RPC server has two allocations + copies - one into a std::string and a second internally within ZMQ. This removes that second copy (but ZMQ still allocates internally!), which is an obvious performance gain.
Its possible to remove the allocation+copy into `bye_slice` by getting `rapidjson` to write directly into a `byte_slice` compatible buffer. I am "saving" that for a future commit because its a bit more code.
I ran with this with clang ASAN mode, no memory leaks detected in the unit tests or in the ZMQ JSON-RPC server usage._
**Unquote**
=> [zmq] use byte_slice for sending zmq messages - removes data copy within zmq

contrib/depends/packages/openssl.mk
I pushed this on monero and forgot to port it on sumo
Ref: https://github.com/monero-project/monero/pull/6414/files
=> [depends] update openssl 1.0.2r

src/cryptonote_basic/difficulty.cpp
Bug introduced on converting difficulty from 64bit to 128bit causing recently synced daemons to display a smaller cumulative difficulty than old ones
=> [difficulty] fix old 128 bit version_2

src/ringct/bulletproofs.cc, src/ringct/rctOps.cpp, src/ringct/rctOps.h, tests/performance_tests/crypto_ops.h, tests/performance_tests/main.cpp, tests/unit_tests/ringct.cpp
Ref: https://github.com/monero-project/monero/pull/6451
**Quote**
_Speeds up Bulletproof verification by eliminating unnecessary point compression and decompression when performing multiply-by-8 operations on group elements to ensure proper subgroup membership._
_Updates performance and unit tests._
_Example speedups on test machine:_
- single 1-output proof: 5.2% speedup
- single 2-output proof: 2.9% speedup
- 4-batch of 2-output proofs: 10.6% speedup
- 64-batch of 2-output proofs: 25.7% speedup
**Unquote**
=> [bulletproofs] verification speedup

src/wallet/wallet2.cpp
on wrong password typed on opening an existing wallet
Error: failed to load wallet: std::exception was printed on exit
instead of
Error: failed to load wallet: invalid password
=> [wallet2] fix catching reason on fail to verify password on wallet opening

src/cryptonote_core/cryptonote_core.cpp
Ok it might be "bad luck" when next block delays (bad luck for the miners i guess...) but for whom is it bad luck when more than the statistically expected blocks pop up during a preset period of time?
Its a shitty phrasing, monero defined a statistical improbabilty with the phrase "bad luck", "coincidence" is the word they were looking for...
=> [cryptonote_core] rephrase warning about hashrate fluctuation

src/cryptonote_basic/cryptonote_format_utils.cpp, src/cryptonote_core/cryptonote_core.cpp
Monero #6472
**Quote**
_An automatic tx variable is initialized properly on the first
run through the loop, but not the second. Moving the variable
inside the loop ensures the ctor is called again to init it._
**Unquote**
=> [cryptonote] fix reuse of non default tx data when relaying

src/cryptonote_core/tx_pool.cpp
Monero #6478
Fixes dandelion tx double spend detection
=> [tx pool] Used legacy category to match insert_key_images behavior

src/cryptonote_protocol/cryptonote_protocol_handler.inl
Monero #6503
BP fork height number adjusted for sumo
**Quote**
_We don't have a function to calculate their weight from a pruned
version (yet)._
**Unquote**
=> [cryptonote_protocol] do not request pruned borromean sig txes

src/cryptonote_core/cryptonote_core.cpp
that was added to follow the past few years monero's six months hardfork schedule
=> [cryptonote_core] remove last scheduled hardfork warning

tests/unit_tests/output_selection.cpp
Following https://github.com/sumoprojects/sumokoin/pull/864 comment
Quote
_(Due to the randomness 0.028 is more or less empirical it might need amendement but i think it will cover almost all cases)_
Unquote
It does need amendment after all, edge cases come up to almost 0.031. It covers them all now.
=> [unit_tests] fix output selection test #2

src/cryptonote_config.h, src/p2p/net_node.inl
We have increased the number of default connections (doubled it) in the past and made peerlist scanning faster.
However we havent increased respectively the whitelist connection percentage thus stressing the node.
=> [p2p] increase whitelist connections number

src/cryptonote_protocol/cryptonote_protocol_handler.inl
Ref Monero #6543
**Quote**
_This can now happen if:_
- we have a pruned db
- we have not connected to the monero network for a while
- we connect to a node
- that node asks us for history
- we only have a pruned version of the most recent common block
_In that case, it's better to not reply but keep the connection alive,
so we can sync off it._
**Unquote**
=> [protocol] don't drop a connection if we can't get a compatible chain

src/cryptonote_config.h, src/cryptonote_core/cryptonote_core.cpp
`BLOCKS_SYNCHRONIZING_DEFAULT_COUNT_PRE_V4`  has no meaning for Sumo
Also fix the name of end of chain default synchronising block count name to `BLOCKS_SYNCHRONIZING_DEFAULT_COUNT_END` so we know what it is for
=> [p2p] fix constant's name and delete obsolete constant

src/blocks/CMakeLists.txt, src/blocks/blocks.cpp
We dont export them and on pedantic they error out as  zero size array
=> [blocks] remove stagenet and testnet

contrib/epee/src/mlocker.cpp
That return was never "happening" where it was, it should be underneath the warning, returning false since query_page_size wont be happening if that clause is true
=> [epee] fix misplaced 'return'

external/db_drivers/liblmdb/mdb.c, src/crypto/tree-hash.c
First one (external/db_drivers/liblmdb/mdb.c_
`char  mn_data[1];` was given a region of 1 byte and by calling memcpy we are trying to write by copying 8 bytes at the below cases
`memcpy(NODEDATA(ni), &my->mc_next_pgno, sizeof(pgno_t));`
`memcpy(ndata, &ofp->mp_pgno, sizeof(pgno_t));`
`memcpy(ndata, data->mv_data, sizeof(pgno_t));`
Second case (src/crypto/tree-hash.c )
We were allocating 32 bytes here `char *ints = calloc(cnt, HASH_SIZE);` and trying to write on it 64 bytes with memcpy below
=> [dbdrivers+crypto] fix a couple of allocated buffer overflows

src/common/utf8.h
```
C:/msys64/home/.../sumokoin/src/common/utf8.h:91:19: warning: comparison is always true due to limited range of data type [-Wtype-limits]
91 |       else if (cp <= 0xffff)
|                ~~~^~~~~~~~~
C:/msys64/home/.../sumokoin/src/common/utf8.h:93:19: warning: comparison is always true due to limited range of data type [-Wtype-limits]
93 |       else if (cp <= 0x10ffff)
```
Its a variadic template and the code is checked twice, once when parsing and once when instantiated.
GCC doesnot understand that this warning isn't always true for all instantiations
So suppress it at this location only rather than globally in cmake. Its a useful warning and we need it otherwise
=> [gcc] fix a warning for latest gcc versions

src/crypto/oaes_lib.c
MINGW hates the fact that timeval struct gives a long int and complains passing `gmtime` from an incompatible pointer type. `gmtime` is time_t and for windows it is a long long. Its an unavoidable trap
Go back to the deprecated ftime just for mingw
=> [crypto] oaes_lib fix for MINGW

contrib/epee/include/net/abstract_tcp_server2.inl
Probably it got screwed up by a recent commit (its for the placeholders compatibility for newer boost versions that we fixed a couple of months ago)
=> [boost] fix a boost include

src/blockchain_db/lmdb/db_lmdb.cpp, src/cryptonote_protocol/cryptonote_protocol_handler.inl
The sync bar and the colors, provided by the ansi escape sequences, are definitely very fancy but for windows it is a gamble cause we dont know if the user's windows system supports ansi colors or if they are enabled. If they are not that beautiful thing turns into a rubbish printout.
So remove the sync bar and the ansi coloring for windows only, keep them for all other OSs
=> [daemon] alter sync display for windows

contrib/epee/include/console_handler.h, contrib/epee/include/net/abstract_tcp_server2.inl, contrib/epee/include/storages/levin_abstract_invoke2.h, src/checkpoints/checkpoints.cpp, src/rpc/rpc_args.cpp, src/simplewallet/simplewallet.cpp, src/wallet/wallet2.cpp
We made core compatible with boost latest but we lost compatibility with old versions like 1.58 due to not recognising boost::placeholders on boost::bind.
=> [core] make compatible with old boost versions

src/blockchain_db/lmdb/db_lmdb.cpp, src/cryptonote_protocol/cryptonote_protocol_handler.inl
Much to my disappointment due to the recent Monero epee tool changes VT100 escape seqeunces are not properly handled by Linux (it was not only windows as I hoped for)
There goes my beloved syncing bar :( (i 'd rater lose the bar than changing code just to keep it)
=> [daemon] remove syncing prgress bar on linux

contrib/epee/include/net/abstract_tcp_server2.inl
On daemon p2p shut down (especially when abruptly with `Ctrl^C` than `exit`) timers are being reset on various p2p objects while they are shutting down hence the red error on logs ` E Setting timer on a shut down object`
Its not an error though its a warning so change it as such
=> [epee] change error to warning

src/rpc/daemon_messages.h
there used to be a `#define COMMA ,` there
=> [rpc] remove obsolete comments

src/cryptonote_basic/cryptonote_format_utils.cpp, src/cryptonote_core/blockchain.cpp, src/cryptonote_core/cryptonote_core.cpp, src/cryptonote_core/cryptonote_tx_utils.cpp, src/wallet/wallet2.cpp, tests/unit_tests/json_serialization.cpp
We start from version 2 our chain's txs are fully encrypted with ringct. 
Cleanup and remove tx version 1 code that applies to Monero only
=> [core] cleanup tx version 1 code

contrib/depends/packages/boost.mk
while trying to cross build, downloading boost libraries from boost org site was impossible due to their reaching their bintray download data limit... checking from boost's github issues this is something that happens regularly and they urge users to try again the next day...
Anyhow grab it always from bitcoin
=> [depends] grab boost from bitcoin core repo always

.github/workflows/build.yml
add a build to the recently added ubuntu 20 (focal fossa) environment to check compatibility with whatever latest it carries (gcc, boost and so on...)
Think that's enough with workflows for the time being
=> [workflows] add an ubuntu 20.04 make release run

src/simplewallet/simplewallet.cpp
There is an ongoing debate at the moment at Monero to include a 26th seed word that will contain the height and/or the timestamp of the moment the wallet was generated so that users wont scan the entire chain "by mistake" and waste time. 
I strongly disagree cause it creates legacy seed words, it will be difficult to communicate and explain and finally if a user wants to use the cli instead of the gui or the web wallet or the android then he should be acquainted with its "features" and particulars. Also Sumo has already 26 seed words with its double checksum so a 27th will be an excess that will complicate things with our webwallet, android and so on. Anyway i added a print of the system's timestamp to facilitate users so they can mark the date down along with their seed words so as they …
=> [simplewallet] print system's timestamp when generating seeds

src/simplewallet/simplewallet.cpp
that's a none deterministic wallet we are creating why was i asking it to show the seeds. (of course it was throwing a "this is not a deterministic wallet" when trying to print them)
=> [simplewallet] fix generate from keys process

src/simplewallet/simplewallet.cpp, src/simplewallet/simplewallet.h
the automatic lock can be annoying so add a `disable_lock` command to disable it from inside the wallet.
You can always lock it manually after that by typing `lock`.
=> [simplewallet] add a disable_lock command

src/common/stack_trace.cpp
ZMQ thread management is a bitch. 
On exiting daemon and killing ZMQ, on linux, below system error is logged 
```
2020-06-17 13:16:43.969	    7f2ad19a9700	INFO	stacktrace	src/common/stack_trace.cpp:133	Exception: std::system_error
2020-06-17 13:16:43.969	    7f2ad19a9700	INFO	stacktrace	src/common/stack_trace.cpp:134	Unwound call stack:
2020-06-17 13:16:43.973	    7f2ad19a9700	INFO	stacktrace	src/common/stack_trace.cpp:172	    [1]  0x10d) [0x5560b16f00cd]:__cxa_throw+0x10d) [0x5560b16f00cd]
2020-06-17 13:16:43.973	    7f2ad19a9700	INFO	stacktrace	src/common/stack_trace.cpp:172	    [2]  0x556) [0x5560b1874a16]:_ZN6detail6expect6throw_ESt10error_codePKcS3_j+0x556) [0x5560b1874a16]
2020-06-17 13:16:43.973	    7f2ad19a9700	INFO	stacktrace	src/common/stack_trace.cpp:172	    [3]  0x53a) …
```
=> [zmq] justify system error on exiting

src/cryptonote_protocol/block_queue.cpp
Trying to fit an uint64_t value (`blockchain_height`) into a uint32_t (`next_unpruned_height`)
=> [cryptonote_protocol] correct types of expression

contrib/epee/include/storages/parserse_base_utils.h
=> [epee] fix array underflow in unicode parsing

.github/workflows/build.yml
it is very often stopping mid-building or installing most likely due to -j 3 overstretching the remote
=> [workflows] dont use more than one thread for openssl on xenial

src/p2p/net_node.h
It was checking in one hour intervals for incoming connections so setting up of IGD port mapping was kicking in late.
decreased to 10 min intervals
=> [p2p] decrease the time we start checking for incoming connections

external/unbound/CMakeLists.txt
fixes below policy warning on cmake 3.12 and beyond
```
Policy CMP0075 is not set: Include file check macros honor
CMAKE_REQUIRED_LIBRARIES.  Run "cmake --help-policy CMP0075" for policy
details.  Use the cmake_policy command to set the policy and suppress this
warning.
```
=> [unbound] fix CMAKE 3.12.0 and newer policy warning

contrib/epee/src/net_ssl.cpp, src/cryptonote_protocol/levin_notify.cpp, src/simplewallet/simplewallet.cpp
suppress `warning: this statement may fall through [-Wimplicit-fallthrough=]` 
In all three specific switch statements, cases are supposed to fallthrough (as commented)  which is why there is no `break`
(warning occurs on gcc 7 upwards, dont know from which version onwards it gets picked up by clang but 11.03 surely picks it up)
(Locally suppressing, with pragmas, a warning both in clang and gcc is hell, as can be seen by the changes, no other way to do this though cause we need this globally)
=> [core] suppress gcc+clang Wimplicit-fallthrough warnings

CMakeLists.txt
fixes `clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]` (present in monero as well) since gcc is ok with `-pie` but clang needs `-Wl, -pie`
=> [clang] fix -pie linker flag for clang

contrib/epee/src/mlog.cpp, src/rpc/core_rpc_server.cpp
Ref: monero 6584
_Quote
It's not something the user needs to know, and will display
attacker controlled data
Unquote_
=> [rpc] don't display invalid json errors on default log level

src/cryptonote_core/tx_pool.cpp
miner tx construction is ok which is why are getting fine coinbase txs but the template creation is such a mess after all dandelion additions from Monero plus our complicated emission scheme. This sloppily fixes the `estimated_reward` variable used only for rpc's `on_get_block_template`. It doesnt actually fix the coinbase reward on the template which isnt a big problem since block weight calculation is ok and txs + fees are included properly, the rest are taken care of by miner tx construction
If we keep this solution we have to update every couple of years (its ok for the next 200k blocks for now)
I ll try to fix it properly in the future (the issue seems to be there from day 1)
(I suppressed locally on the second commit a warning cause by a gcc bug in some versions …
=> [rpc] temporary fix expected_reward

src/blockchain_db/lmdb/db_lmdb.cpp, src/blockchain_db/lmdb/db_lmdb.h
Monero # 6536
Quote
_It'll make it clearer when a DB init failure is due to being
on a filesystem which does not support mmap_
Unquote
=> [lmdb] test for mmap support at init time

src/cryptonote_protocol/levin_notify.cpp
since we have it (thanks to monero) why keeping it secret :)
It pops every ten minutes
=> [dandelion++] print dandelion epoch initialisation on global info instead of debug

src/p2p/net_node.cpp, src/p2p/net_node.h, src/p2p/net_node.inl
**adds a ' --same-version ' option flag to chose whether we want to connect exclusively to remote nodes of the same version as ours**
=> [daemon] add a ' --same-version ' option flag 

.github/workflows/build.yml
cause the pagefile is not providing enough virtual memory for 3 threads and if i increase it there is not enough space to build the huge debug binaries
=> [workflows] reduce threads on windows debug build

src/cryptonote_basic/CMakeLists.txt, src/cryptonote_basic/miner.cpp, src/cryptonote_basic/miner.h, src/daemon/command_parser_executor.cpp, src/daemon/command_server.cpp, src/daemon/rpc_command_executor.cpp, src/daemon/rpc_command_executor.h, src/rpc/core_rpc_server.cpp, src/rpc/core_rpc_server_commands_defs.h, src/rpc/daemon_handler.cpp, src/rpc/daemon_messages.cpp, src/rpc/daemon_messages.h, src/simplewallet/simplewallet.cpp, src/simplewallet/simplewallet.h, src/wallet/api/wallet2_api.h, src/wallet/api/wallet_manager.cpp, src/wallet/api/wallet_manager.h, src/wallet/wallet2.cpp, src/wallet/wallet2.h, src/wallet/wallet_rpc_server.cpp, src/wallet/wallet_rpc_server.h, src/wallet/wallet_rpc_server_commands_defs.h, tests/functional_tests/mining.py, utils/python-rpc/framework/daemon.py, utils/python-rpc/framework/wallet.py
Remove smart background mining (along with references) completely from core (along with the useless ignore battery and ac power stuff). It was introduced by monero for reasons best known to themselves... It might have been a vain attempt to decentralise mining or something back in the day...
Tested the branch on testnet. Manual setting of mining on a testnet daemon is finding blocks just fine. Arguments introduction is ok both when entered on daemon and the cli and autodetection of threads is fine.
=> [core] completely remove smart background mining

contrib/epee/include/storages/levin_abstract_invoke2.h
Fixed a whitespace after a backslash and also removed a comment cause it scares clang away thinking that the line below maybe included to the line above giving a `backslash and newline separated by space [-Wbackslash-newline-escape]` warning
=> [epee] fix comment + backslash

src/mnemonics/chinese_simplified.h, src/mnemonics/dutch.h, src/mnemonics/english.h, src/mnemonics/english_old.h, src/mnemonics/esperanto.h, src/mnemonics/french.h, src/mnemonics/german.h, src/mnemonics/italian.h, src/mnemonics/japanese.h, src/mnemonics/language_base.h, src/mnemonics/lojban.h, src/mnemonics/portuguese.h, src/mnemonics/russian.h, src/mnemonics/spanish.h
Some of the benefits of C++17...
Make seed words list creation much faster by replacing `const char *` with `std::string_view`
=> [mnemonics] replace const char* with C++17's std::string_view

src/cryptonote_config.h
it should have been updated in our latest release as well (it uses the last checkpoint height to drop the block sync size to 1 from 50 after the precompiled blocks.dat file is exhausted) it will drop to 1 at 435000 instead of 446000 no big deal
=> [checkpoints] update last checkpoint on config.h

src/blockchain_db/blockchain_db.cpp, src/blockchain_db/blockchain_db.h, src/cryptonote_config.h, src/cryptonote_core/cryptonote_core.cpp, src/cryptonote_core/tx_pool.cpp, src/cryptonote_protocol/cryptonote_protocol_handler.inl, src/cryptonote_protocol/enums.h, src/cryptonote_protocol/levin_notify.cpp, tests/unit_tests/levin.cpp
Ref Monero # 6354
**Quote**
_The last bullet point on the CCS for transaction privacy is a randomized delay before a node takes an incoming transaction from i2p/tor and sends it over ipv4/6. My thought was an attempt to conceal the bandwidth/timing analysis of i2p/tor. If the the i2p/tor hidden service only has one incoming connection, this delay possibly/probably does nothing. But if the hidden service has 2+ incoming connections sending white noise, the transaction could've been received over any of the white noise connections._
_This creates another mempool state._
**Unquote**
=> [p2p] Add randomized delay when forwarding txes from i2p/tor -> ipv4/6

contrib/epee/include/storages/portable_storage_val_converters.h
epee tools are getting really cumbersome and deprecated...
that code snippet was producing already a "comparison of integer expressions of different signedness" warning on gcc and clang,  judging by the pragma pushes that were already there. They are not effective for gcc 9.3, I am not going to struggle, I am leaving these there and re-suppressed throughout the snippet...
=> [epee] re-suppress warning caught on gcc 9.3

CMakeLists.txt
Sumokoin needs at the moment on about 3 Gb of available memory (physical + virtual ) to compile, check that, right off the start, at CMake (give it some room of 500 Mb extra in order to be safe on all systems)
=> enforce minimum available memory for compilation

src/simplewallet/simplewallet.cpp
Adds an `address_book export` command which exports all entries of the wallet's address book into an address_book.txt file
Second commit adds `address_book export_csv` command which exports all entries of the wallet's address book (in csv format) into an address_book.csv file
Also rearranged the entire address_book function to be a bit more straightforward.
Screen printout of the address book is now executed with `address_book show`
=> [simplewallet] Add export address book to a file commands (in csv or txt format)

.github/workflows/build.yml
get latest version (1.74.0) from boost.org for the few build cases we compile it ourselves
=> [workflows] upgrade boost to latest and update link

src/blockchain_utilities/blockchain_stats.cpp
Various improvements and fixes on blockchain_stats utility ported from Monero
- Tweak format, add option for difficulty
Set input, output, ringsize averages to 2 decimal places precision
Add option to show min/max/av per-block difficulty
- Add options to print daily coin emission and fees
- Don't forget size of prunable txn part
=> [blockchain_stats] various improvements and fixes

tests/functional_tests/check_missing_rpc_methods.py, utils/python-rpc/framework/daemon.py
=> [python-rpc] add missing sync_txpool python entry point and add missing error when an entry point is missing

contrib/epee/include/console_handler.h, src/daemon/command_server.cpp, src/daemon/command_server.h, src/simplewallet/simplewallet.cpp, src/simplewallet/simplewallet.h
This is partially based on Monero # 6614 where they reverted the help_advanced configuration (we reverted that ourselves some months ago) and added a command to search wallet's or daemon's command help list by keyword.
They named the command `apropos` (i guess to sound sophisticated) i renamed it to `search_command` and adjusted the code for sumo
Anyhow, it's useful, i ll use that tool to search the address book entries by keyword on description on a next pr
=> [simplewallet + daemon] Add new 'search_command' command

src/simplewallet/simplewallet.cpp, src/wallet/wallet2.cpp, src/wallet/wallet2.h
Monero Ref # 6752
**Quote**
_insert doesn't actually insert if another element with the
same key is already in the map_
**Unquote**
adjusted slightly for sumo
=> [wallet2] fix setting tx keys when another is already set

src/rpc/core_rpc_server.cpp
Ref Monero # 6763
**Quote**
_It turns out that some remote (bootstrap) nodes silently drop / don't broadcast client's transactions._
**Unquote**
=> [rpc] always send raw txes through P2P (don't use bootstrap daemon)

contrib/epee/include/byte_stream.h, tests/unit_tests/epee_utils.cpp
=> [epee] add clear method to byte_stream

src/cryptonote_config.h, src/cryptonote_core/blockchain.cpp, tests/core_tests/block_validation.cpp, tests/core_tests/block_validation.h, tests/core_tests/chaingen_main.cpp
Ref Monero # 6760 adjusted for sumo
**Quote**
Claiming a slightly lesser amount does not yield the size gains that were seen pre rct, so this closes a fingerprinting vector
**Unquote**
**This will need a hardfork, it can be on the same HF as CLSAG.
Version number (10) and alias has been defined in cryptonote_config, no height entered till we decide**
=> [core] enforce claiming maximum coinbase amount [needs an HF]

README.md
minimum gcc 5.4 to be able to make use of c++17
libusb-dev -> libusb-1.0 specific ( i saw this in monero, fixes a silly cmake warning, i think i have fixed that in our cmake in the past but change it anyhow)
add libudev which is needed in static
add unbound on mingw deps
=> [readme] update dependencies

CMakeLists.txt
Reference https://gcc.gnu.org/onlinedocs/gnat_ugn/Compilation-options.html
(gcc + Linux only)
Change in size is quite dramatic
(make release-static)
**Before**
**After**
Exe files built with mingw are unaffected
=> [cmake -gcc-linux] reduce static produced binaries by more than 50% in size

src/cryptonote_core/blockchain.cpp
=> [blockchain] fix pow skipping for old blocks without precalc hash

src/hardforks/hardforks.cpp
HF 11 should happen one or two days after HF 10.
https://github.com/sumoprojects/sumokoin/blob/dev/src/cryptonote_core/blockchain.cpp#L2845
HF 10 introduces CLSAG and allows both SAGs - HF 11 forbids the coexistence of MLSAG and CLSAG in favour of CLSAG
=> [hardforks] add placeholder for HF 11

src/daemon/command_parser_executor.cpp, src/daemon/command_server.cpp, src/p2p/net_node.inl
Added the ability to permanent ban an IP by typing on daemon `ban <IP> -1`
This besides banning the IP permanently, on that daemon instance, exports the permanently banned IPs on a file called "bannedips" which is read every time a new daemon instance starts and all the IPs contained in that file are autobanned indefinitely.
(permanently banned ips can be removed by editing that file)
=> [daemon+p2p] add option to ban nodes permanently

src/daemon/command_parser_executor.cpp, src/daemon/rpc_command_executor.cpp, src/p2p/net_node.inl
=> [p2p+daemon] use time_t numeric limit instead of a random big number when permabanning and show that a node is permanently banned on print_bans

CMakeLists.txt, cmake/FindBoost.cmake, cmake/FindPackageHandleStandardArgs.cmake, cmake/FindPackageMessage.cmake
Gets rid of warnings caused by old cmake versions trying to identify latest boost versions without needing to upgrade cmake. 
We met them especially while cross-compiling 
For example in cross building windows binaries  it now beautifully prints 
while before we were getting
=> [cmake+boost] enable older versions of cmake to find and identify new versions of boost properly

src/p2p/net_node.h, src/p2p/net_node.inl
we were telling daemon to always use the hardcoded seeds but it was still always resolving the DNS seed nodes counting them to be added. Properly clean it up. Improves speed of initialization of syncing on fresh daemons with no peerlist yet
=> [p2p] remove lookup for DNS seed nodes

src/crypto/jh.c
stole this workaround from another coin (loki) which was getting a stuck blockchain caused by inability to hash beyond a certain block due to the way this pointer part was optimized when compiled with gcc 10.
We were just getting uninitialized warnings which are now gone.
Synced from scratch all the way, it is fine.
=> [crypto] fix warnings on obscure old c code in jh.c

src/cryptonote_core/blockchain.cpp
that was throwing variable unused warnings on latest versions of gcc
=> [core] suppress gcc-10 useless warning

src/cryptonote_protocol/cryptonote_protocol_handler.inl
it displays the same from 0 block when we are in not fast sync mode `--fast-block-sync=0`
=> [daemon] mention when we leave the compiled block hashes area and syncing is dealyed

src/cryptonote_config.h, src/cryptonote_core/cryptonote_core.cpp
revert it to 10 from 50  (the gain in time is almost zero) and revert the end of chain decrease to 1 (which was buggy) for the same reason
=> [block_sync_size] revert the default to 10 blocks per batch

contrib/epee/include/console_handler.h, contrib/epee/include/net/abstract_tcp_server2.h, contrib/epee/include/net/abstract_tcp_server2.inl, contrib/epee/include/net/abstract_tcp_server_cp.inl, contrib/epee/include/net/levin_client_async.h, contrib/epee/include/net/levin_protocol_handler_async.h, contrib/epee/include/net/net_helper.h, contrib/epee/include/storages/levin_abstract_invoke2.h, src/common/threadpool.cpp, src/cryptonote_basic/miner.cpp, src/cryptonote_core/blockchain.cpp, src/cryptonote_core/cryptonote_core.cpp, src/cryptonote_protocol/cryptonote_protocol_handler.inl, src/p2p/net_node.inl, src/rpc/rpc_args.cpp, src/rpc/zmq_server.cpp, src/simplewallet/simplewallet.cpp, src/wallet/wallet2.cpp
where no code refactoring is needed (for example where an std::map is not involved).
Avoid the boost placeholders issue with boost versions altogether as well
Parts we dont build like trezor were left unchanged
=> [boost->std] replace boost::bind with std::bind where possible

src/p2p/net_node.inl
fix default seed nodes lookup (that's a fix on this recent commit https://github.com/sumoprojects/sumokoin/commit/09f8c898a41e30a0748d50634d2a5f56469455e2)
=> [p2p] fix seed nodes lookup

CMakeLists.txt
dead-strip option flag for bin compression when building on clang gives a segfault (noticed on freebsd, macos seems ok)
=> [clang] remove dead-strip for clang builds other than apple (bin compression)

src/cryptonote_core/cryptonote_core.h, src/cryptonote_core/i_core_events.h, src/cryptonote_protocol/cryptonote_protocol_handler.inl, src/cryptonote_protocol/levin_notify.cpp, src/cryptonote_protocol/levin_notify.h, src/p2p/net_node.h, src/p2p/net_node.inl, src/p2p/net_node_common.h, tests/unit_tests/levin.cpp
monero ref # 6875
thats a mighty unnecessarily complicated fix but bring it in the way it is for compatibility
=> [dandelion++] skip desynced peers in stem phase

src/hardforks/hardforks.cpp
Testnet
HF 10 Height 231500 Timestamp 1603158050  // CLSAG & EXACT COINBASE
HF 11 Height 233500 Timestamp 1603638050 // FORBID MLSAG ALLOW CLSAG ONLY
=> [testnet HF-CLSAG] set hardfork heights and timestamps for HF10 & HF 11

src/cryptonote_core/blockchain.cpp, src/hardforks/hardforks.cpp, src/hardforks_checkpoints_config.h
it was breaking block verification due to our emission scheme. it is not a feature worth thinking about twice anyhow.
resetting testnet hf a bit higher
=> [testnet-HF10] revert enforce claiming maximum coinbase amount and move testnet HF a bit higher

src/cryptonote_core/tx_pool.cpp
monero ref # 6880 
till the bug throwing `failed to find tx meta` warning is fixed
=> [tx_pool] temporarily silence spammy harmless warning

.github/workflows/build.yml, contrib/epee/include/serialization/keyvalue_serialization_overloads.h, contrib/epee/include/storages/portable_storage.h, src/blockchain_db/blockchain_db.cpp, src/wallet/wallet2.cpp
Needs a release.
No need to change the entire output selection distribution pattern for a bit of distribution selection skewing 
Our txs are few, our ring size is enormous and the skewing is insignificant, it wont make any difference so just cover the extreme case of average_output_time == 0 to avoid the division with zero here   `uint64_t output_index = x / average_output_time;`
Funny thing is that on wallet2 header file average_output_time is already declared as double so i guess they forgot to cast it when they introduced that bit of code
=> [wallet2] fix precision of average_output_time and harden code against invalid input types
